/**
 * THE ABYSS'S SURFACES: floor, wall and rock as albedo + normal + roughness,
 * and the painted marks (the circle, magma, blood) as decals — all written to
 * `src/abyss/assets/world.ts` as data URIs.
 *
 *   npx tsx tools/abyss/tex.mts
 *
 * The generator was asked for SEAMLESS surfaces and delivered them — tiled 2x2
 * none of the three shows an edge — so nothing here blends seams; a normal and
 * a roughness map are derived off the albedo's own height.
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const CACHE = 'tools/abyss/cache';
const WORK = join(CACHE, 'tex');
mkdirSync(WORK, { recursive: true });
const py = (...args: string[]): string => execFileSync('python3', ['tools/abyss/img.py', ...args], { encoding: 'utf8' }).trim();

const SURFACES: { id: string; src: string; px: number; bump: number; rough: [number, number] }[] = [
  { id: 'floor', src: 'floor_stone-0', px: 1024, bump: 9, rough: [0.78, 0.5] },
  { id: 'wall', src: 'wall_stone-0', px: 1024, bump: 7, rough: [0.84, 0.4] },
  { id: 'rock', src: 'rock-0', px: 1024, bump: 11, rough: [0.7, 0.55] },
];
const DECALS: { id: string; src: string; px: number; mode: 'red' | 'light' }[] = [
  { id: 'circle', src: 'circle-0', px: 1024, mode: 'light' },
  { id: 'magma', src: 'magma-0', px: 1024, mode: 'light' },
  { id: 'blood', src: 'blood-0', px: 512, mode: 'red' },
];

const uri = (file: string, mime: string): string => `data:${mime};base64,${readFileSync(file).toString('base64')}`;
const lines = [
  `// GENERATED by tools/abyss/tex.mts — never edited by hand. Meshy surfaces and decals.`,
  `import type { WorldShard } from '../assets';`,
  `export const SHARD: WorldShard = {`,
];
for (const s of SURFACES) {
  const src = join(CACHE, `${s.src}.png`);
  const out = (k: string) => join(WORK, `${s.id}-${k}.jpg`);
  py('resize', src, out('albedo'), String(s.px), '90');
  py('normal', src, out('normal'), String(s.px), String(s.bump));
  py('rough', src, out('rough'), String(s.px / 2), String(s.rough[0]), String(s.rough[1]));
  lines.push(`  ${s.id}: { albedo: '${uri(out('albedo'), 'image/jpeg')}', normal: '${uri(out('normal'), 'image/jpeg')}', rough: '${uri(out('rough'), 'image/jpeg')}' },`);
  console.log(`${s.id}: albedo, normal, roughness`);
}
for (const d of DECALS) {
  const out = join(WORK, `${d.id}.${d.mode === 'red' ? 'png' : 'jpg'}`);
  py('alpha', join(CACHE, `${d.src}.png`), out, String(d.px), d.mode);
  lines.push(`  ${d.id}: { albedo: '${uri(out, d.mode === 'red' ? 'image/png' : 'image/jpeg')}' },`);
  console.log(`${d.id}: decal`);
}
for (const w of [{ id: 'rose', white: false }, { id: 'lancet', white: true }]) {
  const out = join(WORK, `${w.id}.jpg`);
  py(w.white ? 'unwhite' : 'resize', join(CACHE, `${w.id}-0.png`), out, '1024', ...(w.white ? [] : ['90']));
  lines.push(`  ${w.id}: { albedo: '${uri(out, 'image/jpeg')}' },`);
  console.log(`${w.id}: glass`);
}
const ICONS: [string, string][] = [['icon_arc', 'none'], ['icon_blink', '0.06,0.06,0.94,0.94'], ['icon_life', '0.02,0.1,0.66,0.9'], ['icon_mana', '0.1,0.1,0.9,0.9']];
for (const [id, crop] of ICONS) {
  const out = join(WORK, `${id}.jpg`);
  py('icon', join(CACHE, `${id}-0.png`), out, '128', crop);
  lines.push(`  ${id}: { albedo: '${uri(out, 'image/jpeg')}', icon: true },`);
  console.log(`${id}: icon`);
}
lines.push('};', '');
writeFileSync('src/abyss/assets/world.ts', lines.join('\n'));
console.log(`world: ${(readFileSync('src/abyss/assets/world.ts').byteLength / 1048576).toFixed(1)} MB as text`);
