/**
 * The bestiary. Same shape as the armour families: a creature declares its own
 * inks and its own frames, so nine of them share one alphabet in the source and
 * none of them share a colour on screen.
 *
 * `x` is the RANK accent — dull on a common one, lit on a magic, blazing on a
 * rare. The rank also grows the body and puts a halo round it; see `haloed`.
 */
import { gridRows, mix } from './gear-art';
import { GENERATED } from './generated-art';
import type { Palette } from './renderer';

export interface BeastTone {
  mass: (p: Palette) => string;
  lit: (p: Palette) => string;
  shade: (p: Palette) => string;
  eye: (p: Palette) => string;
}

export interface BeastArt {
  tone: BeastTone;
  /** Side of the grid this creature is drawn on. Its own, so the bestiary can
   *  be redrawn a family at a time without the pipeline caring. */
  grid: number;
  frames: [string[], string[]];
  /** The swing. Absent means it has none yet and stands still to hit you. */
  attack?: string[];
}

/** Every creature declares the grid it was drawn on; this is what they use. */
const rows = gridRows(24);

export const BEASTIARY: Record<string, BeastArt> = {
  /**
   * The Astral-Geometer: upright and still, both hands up holding a shard to
   * the light. The one body down here that is not going anywhere — where the
   * Osteomancer stoops and reaches, this one is measuring.
   */
  geometer: {
    tone: {
      mass: (p) => mix(p.rose, p.gloom, 0.35),
      lit: (p) => mix(p.blush, p.rose, 0.3),
      shade: (p) => mix(p.gloom, p.void, 0.3),
      eye: (p) => p.pearl,
    },
    grid: 24,
    frames: [
      rows({
        4: '.................#......',
        5: '..........####..#M#.....',
        6: '.........#MMMM#.#ee#....',
        7: '........#mmmmmm##ee#....',
        8: '........#mMMMem#.##.....',
        9: '........#mMMMMm##M#.....',
        10: '........#sMMMM#.#m#.....',
        11: '........#mMMMMs##m#.....',
        12: '........#mmmmssmm#......',
        13: '........#mmMmss##.......',
        14: '.......#mmmMmmss#.......',
        15: '.......#mmmMmmss#.......',
        16: '.......#mmmMmmss#.......',
        17: '......#mmmmMmmmss#......',
        18: '......#mmmmMmmmss#......',
        19: '......#mmmmMmmmss#......',
        20: '.....#mmmmmmmmmmss#.....',
        21: '.....#mmmmmmmmmmss#.....',
        22: '......############......',
      }),
      rows({
        5: '..........####...#......',
        6: '.........#MMMM#.#M#.....',
        7: '........#mmmmmm##ee#....',
        8: '........#mMMMem##ee#....',
        9: '........#mMMMMm##M#.....',
        10: '........#sMMMM#.#m#.....',
        11: '........#mMMMMs##m#.....',
        12: '........#mmmmssmm#......',
        13: '........#mmMmss##.......',
        14: '.......#mmmMmmss#.......',
        15: '.......#mmmMmmss#.......',
        16: '.......#mmmMmmss#.......',
        17: '......#mmmmMmmmss#......',
        18: '......#mmmmMmmmss#......',
        19: '......#mmmmMmmmss#......',
        20: '.....#mmmmmmmmmmss#.....',
        21: '.....#mmmmmmmmmmss#.....',
        22: '......############......',
      }),
    ],
  },

  /**
   * The Osteomancer: starved. A skull too big for the body under it, a bone
   * half-mask shoved up on the brow, and both hands out — nothing else down
   * here wants anything from you. The silhouette carries it: the head is ten
   * pixels across and the chest is six, and the gap between his arms and his
   * ribs is most of what says he is not strong enough to take what he asks for.
   */
  osteomancer: {
    tone: {
      mass: (p) => mix(p.flesh, p.gore, 0.4),
      lit: (p) => mix(p.fleshLit, p.sinew, 0.3),
      shade: (p) => mix(p.gore, p.char, 0.45),
      eye: (p) => p.venom,
    },
    grid: 24,
    frames: [
      rows({
        3: '.........######.........',
        4: '........#Mmmmmms#.......',
        5: '.......#Mbbbbbbs#.......',
        6: '.......#MMmmmmms#.......',
        7: '.......#Mmeemees#.......',
        8: '.......#Mmmsmmss#.......',
        9: '........#Mm###s#........',
        10: '.........#Mmms#.........',
        11: '.....#Mm#.#ms#..........',
        12: '....#MMmmmmms#..........',
        13: '....#MMmsm##########....',
        14: '....#MMmmsmmmmmmmmmm#...',
        15: '....#Mmmss#######mmms#..',
        16: '....#MMmms#####.#####...',
        17: '....#Mmmssmmmmm#........',
        18: '....#Mmmss#####.........',
        19: '....#Mmmsmmms#..........',
        20: '....#Mm#..#ms#..........',
        21: '...#mmm#..#mmm#.........',
        22: '...#####..#####.........',
      }),
      rows({
        3: '.........######.........',
        4: '........#Mmmmmms#.......',
        5: '.......#Mbbbbbbs#.......',
        6: '.......#MMmmmmms#.......',
        7: '.......#Mmeemees#.......',
        8: '.......#Mmmsmmss#.......',
        9: '........#Mm###s#........',
        10: '.........#Mmms#.........',
        11: '.....#Mm#.#ms#..........',
        12: '....#MMmmmmms#..........',
        13: '....#MMmsm######........',
        14: '....#MMmmsmmmmmm#.......',
        15: '....#Mmmss#####mmmm#....',
        16: '....#MMmms######mmms#...',
        17: '....#Mmmssmmmmm#.####...',
        18: '....#Mmmss#####.........',
        19: '....#Mmmsmmms#..........',
        20: '...#mmm#..#ms#..........',
        21: '...#####..#mmm#.........',
        22: '..........#####.........',
      }),
    ],
  },

  /**
   * The Lambengolmor: upright where the Lampwright stoops, bare-headed where he
   * is hooded, and carrying a rule rather than a lamp. Pale and cold — he is
   * the one who thinks the rock can be read.
   */
  lambengolmor: {
    tone: {
      mass: (p) => mix(p.bone, p.rockDeep, 0.45),
      lit: (p) => mix(p.bone, p.chalk, 0.3),
      shade: (p) => mix(p.bone, p.void, 0.62),
      eye: (p) => p.amethyst,
    },
    grid: 24,
    frames: [
      rows({
        2: '.........######.........',
        3: '........#mssssm#........',
        4: '........#mmmmmm#........',
        5: '........#mMMMMm#........',
        6: '........#meMMem#........',
        7: '........#mMssMm#........',
        8: '.......#mmmmmmms#.......',
        9: '.......#mmmmemss#.......',
        10: '.......#mmMmmmss#.......',
        11: '.......#mmMmmmss#.......',
        12: '......#mmmeemmmss#......',
        13: '......#mmmMmmmmsmm#.....',
        14: '......#mmmMmmmmssm#.....',
        15: '......#mmmMmemmss#......',
        16: '.....#mmmmMmmmmmss#.....',
        17: '.....#mmmmMmmmmmss#.....',
        18: '.....#mmmmMemmmmss#.....',
        19: '.....#mmmmMmmmmmss#.....',
        20: '....#mmmmmmmmmmmmss#....',
        21: '....#mmmmmmmmmmmmss#....',
        22: '.....##############.....',
      }),
      rows({
        2: '.........######.........',
        3: '........#mssssm#........',
        4: '........#mmmmmm#........',
        5: '........#mMMMMm#........',
        6: '........#meMMem#........',
        7: '........#mMssMm#........',
        8: '.......#mmmmmmms#.......',
        9: '.......#mmmmemss#.......',
        10: '.......#mmMmmmss#.......',
        11: '.......#mmMmmmss#.......',
        12: '......#mmmMemmmss#......',
        13: '......#mmmemmmmsmm#.....',
        14: '......#mmmMmmmmssm#.....',
        15: '......#mmmMmemmss#......',
        16: '.....#mmmmMmmmmmss#.....',
        17: '.....#mmmmMmmmmmss#.....',
        18: '.....#mmmmMemmmmss#.....',
        19: '.....#mmmmMmmmmmss#.....',
        20: '....#mmmmmmmmmmmmss#....',
        21: '....#mmmmmmmmmmmmss#....',
        22: '.....##############.....',
      }),
    ],
  },

  /**
   * What answers to its name: the rock itself stood up, with a seam lit through
   * it and eyes it did not have a moment ago. WIDE rather than tall — the thing
   * you cannot get round — and the seam is what widens when it swings.
   */
  answering: {
    tone: {
      mass: (p) => mix(p.rock, p.rockDeep, 0.5),
      lit: (p) => mix(p.rock, p.chalk, 0.28),
      shade: (p) => mix(p.rockDeep, p.void, 0.5),
      eye: (p) => p.amethyst,
    },
    grid: 24,
    frames: [
      rows({
        1: '.......##########.......',
        2: '.....##MMMMmmmmmss##....',
        3: '...##MMMMmmmmmmmmmsss##.',
        4: '..#MMMMmmmmeemmmmmmsss#.',
        5: '..#MMMmmmmeooemmmmmmss#.',
        6: '.#MMMmmmmmeooemmmmmmsss#',
        7: '.#MMmmmmmmmeemmmmmmmsss#',
        8: '.#MMmmeemmmmmmmmeemmsss#',
        9: '.#MMmmeemmmmmmmmeemmsss#',
        10: '.#MMmmmmmmmmmmmmmmmmsss#',
        11: '..#MMmmmmmmmmmmmmmmsss#.',
        12: '..#MMmmmmoooooommmsssss#',
        13: '...#MMmmmmmmmmmmmmsss#..',
        14: '...#MMmmmmmmmmmmmmsss#..',
        15: '..##MMmmmmmmmmmmmmsss##.',
        16: '.#MMMmmmm########mmmsss#',
        17: '.#MMmmmm#........#mmsss#',
        18: '.#MMmmm#..........#msss#',
        19: '.#MMmm#............#sss#',
        20: '.#Mmm#..............#ss#',
        21: '.#mm#................#s#',
        22: '.####..................#',
      }),
      rows({
        1: '.......##########.......',
        2: '.....##MMMMmmmmmss##....',
        3: '...##MMMMmmmmmmmmmsss##.',
        4: '..#MMMMmmmmeemmmmmmsss#.',
        5: '..#MMMmmmmeooemmmmmmss#.',
        6: '.#MMMmmmmmeooemmmmmmsss#',
        7: '.#MMmmmmmmmeemmmmmmmsss#',
        8: '.#MMmmeemmmmmmmmeemmsss#',
        9: '.#MMmmeemmmmmmmmeemmsss#',
        10: '.#MMmmmmmmmmmmmmmmmmsss#',
        11: '..#MMmmmmmmmmmmmmmmsss#.',
        12: '..#MMmmmoooooooommsssss#',
        13: '...#MMmmmmmmmmmmmmsss#..',
        14: '...#MMmmmmmmmmmmmmsss#..',
        15: '..##MMmmmmmmmmmmmmsss##.',
        16: '.#MMMmmm##########mmsss#',
        17: '.#MMmmm#..........#msss#',
        18: '.#MMmm#............#sss#',
        19: '.#MMm#..............#ss#',
        20: '.#Mm#................#s#',
        21: '.#m#..................##',
        22: '.##....................#',
      }),
    ],
    attack: rows({
      1: '.....##MMMMMMMMmmss##...',
      2: '...##MMMMmmmmmmmmmsss##.',
      3: '..#MMMMmmmmmmmmmmmmsss#.',
      4: '.#MMMMmmmmmeemmmmmmssss#',
      5: '.#MMMmmmmmeoooemmmmmsss#',
      6: '.#MMMmmmmmeoooemmmmmsss#',
      7: '.#MMmmmmmmmeeemmmmmmsss#',
      8: '.#MMmeeemmmmmmmmeeemsss#',
      9: '.#MMmeeemmmmmmmmeeemsss#',
      10: '.#MMmmmmmmmmmmmmmmmmsss#',
      11: '.#MMmmmmooooooooommmsss#',
      12: '.#MMmmmmooooooooommmsss#',
      13: '..#MMmmmmmmmmmmmmmsss#..',
      14: '..#MMmmmmmmmmmmmmmsss#..',
      15: '.##MMmmmmmmmmmmmmmsss##.',
      16: '#MMMmm##########mmmssss#',
      17: '#MMmm#............#msss#',
      18: '#MMm#..............#sss#',
      19: '#MM#................#ss#',
      20: '#Mm#.................#s#',
      21: '#m#...................##',
      22: '##.....................#',
    }),
  },

  /** Low, wide and segmented. Almost no vertical presence: the thing you walk over. */
  grub: {
    tone: {
      mass: (p) => mix(p.verdite, p.rockDeep, 0.42),
    lit: (p) => mix(p.verdite, p.chalk, 0.22),
    shade: (p) => mix(p.verdite, p.void, 0.55),
    eye: (p) => p.citrine,
    },
    grid: 24,
    frames: [
      rows({
        7: '.....##############.....',
        8: '...##mmmmmmmmmmmmmm##...',
        9: '..#mMsMMsMMsMMsMMsMMm#..',
        10: '..#MMsMMsMMsMMsMMsMMe#..',
        11: '..#MMsMMsMMsMMsMMsMMx#..',
        12: '..#MMsMMsMMsMMsMMsMMe#..',
        13: '..#mMsMMsMMsMMsMMsMMm#..',
        14: '...##mmmmmmmmmmmmmm##...',
        15: '...#s##s##s##s##s##m#...',
        16: '...#.#..#..#..#..#.#....',
      }),
      rows({
        7: '.....##############.....',
        8: '...##mmmmmmmmmmmmmm##...',
        9: '..#mMsMMsMMsMMsMMsMMm#..',
        10: '..#MMsMMsMMsMMsMMsMMe#..',
        11: '..#MMsMMsMMsMMsMMsMMx#..',
        12: '..#MMsMMsMMsMMsMMsMMe#..',
        13: '..#mMsMMsMMsMMsMMsMMm#..',
        14: '...##mmmmmmmmmmmmmm##...',
        15: '...##m##m##m##m##m##....',
        16: '.....#..#..#..#..#......',
      }),
    ],
    attack: rows({
      3: '...............#####....',
      4: '..............#msem#....',
      5: '..............#seeM#....',
      6: '.............##mMx#.....',
      7: '........##########......',
      8: '.....##Mmmmmmmmmm##.....',
      9: '....#mMsMMsMMsMMsM#.....',
      10: '...#MMsmMsmMsmMsmM#.....',
      11: '...#MMsMMsMMsMMsM#......',
      12: '...#mMsMMsMMsMMsMM#.....',
      13: '...##mmmmmmmmmmmm##.....',
      14: '....#s##s##s##s##m#.....',
      15: '....#.#..#..#..#.#......',
    }),
  },
  /** A person, badly. Sunken eyes, a rib showing, arms too long for it. */
  husk: {
    tone: {
      mass: (p) => mix(p.bone, p.rockDeep, 0.5),
      lit: (p) => mix(p.bone, p.chalk, 0.3),
      shade: (p) => mix(p.bone, p.void, 0.62),
      eye: (p) => mix(p.venom, p.chalk, 0.2),
    },
    // The first creature off the generator: 256, and three frames of its own
    // rather than two and a reused pose.
    grid: GENERATED.goth_a.grid,
    frames: [GENERATED.goth_a.frames[0], GENERATED.goth_a.frames[1]],
    attack: GENERATED.goth_a.frames[2],
  },
  stalker: {
    tone: {
      mass: (p) => mix(p.citrine, p.rockDeep, 0.48),
    lit: (p) => mix(p.citrine, p.chalk, 0.25),
    shade: (p) => mix(p.citrine, p.void, 0.6),
    eye: (p) => p.ember,
    },
    grid: 24,
    frames: [
      rows({
        5: '..................####..',
        6: '.......###########mMMe#.',
        7: '....#MMsMMsMMsMMMMMx#...',
        8: '..#MMsMmsMmsMmMMMM##....',
        9: '..#MMsMMsMMsMMMMM#......',
        10: '..#mMsMMsMMsMMM#........',
        11: '..#m##MM##Mm##s#........',
        12: '..#M#.#M#.#M#...........',
        13: '..#M#.#M#.#M#...........',
        14: '..#M#.#M#.#M#...........',
        15: '..##..##..##............',
      }),
      rows({
        5: '..................####..',
        6: '.......###########mMMe#.',
        7: '....#MMsMMsMMsMMMMMx#...',
        8: '..#MMsMmsMmsMmMMMM##....',
        9: '..#MMsMMsMMsMMMMM#......',
        10: '..#mMsMMsMMsMMM#........',
        11: '..#m##MM##Mm##s#........',
        12: '...#M#.#M#.#M#..........',
        13: '.#M#..#M#..#M#..........',
        14: '#M#...#M#..#M#..........',
        15: '##....##...##...........',
      }),
    ],
    attack: rows({
      7: '...................####.',
      8: '......############MMMe#.',
      9: '..#MMsMMsMMsMMMMMMx#....',
      10: '#MMsMmsMmsMmMMMMM##.....',
      11: '.#MmsMmsMmsMMMMM#.......',
      12: '.#m##MM##Mm##s#.........',
      13: '.#M#.#M#.#M#............',
      14: '#M#..#M#..#M#...........',
      15: '##...##....##...........',
    }),
  },
  /** A slab with a head sunk into it. Shoulders wider than anything else down here. */
  brute: {
    tone: {
      mass: (p) => mix(p.ember, p.rockDeep, 0.45),
    lit: (p) => mix(p.ember, p.citrine, 0.3),
    shade: (p) => mix(p.ember, p.void, 0.62),
    eye: (p) => p.flame,
    },
    grid: 24,
    frames: [
      rows({
        2: '.....##############.....',
        3: '.....#mMMMMMMMMMMm#.....',
        4: '.....#seMMMMMMMMes#.....',
        5: '.....##mMMMxxMMMm##.....',
        6: '....###MMMMMMMMMM###....',
        7: '...#mMMMMMsxxsMMMMMs#...',
        8: '#MMMMMMsxxsMMmMMM#......',
        9: '#mMMMMMsxxsMMMMMm#......',
        10: '#MMMMMMssssMMMMMM#......',
        11: '#mMMMMMssssMMMMMm#......',
        12: '#MMMMMMmmmmMMMMMM#......',
        13: '.##MMMM####MMMM##.......',
        14: '...#MMm#..#mMM#.........',
        15: '...#MM#....#MM#.........',
        16: '...#MM#....#MM#.........',
        17: '...#Mm#....#mM#.........',
        18: '...#MM#....#MM#.........',
        19: '...#MM#....#MM#.........',
        20: '...##mm#..#mm##.........',
        21: '...#####..#####.........',
      }),
      rows({
        2: '.....##############.....',
        3: '.....#mMMMMMMMMMMm#.....',
        4: '.....#seMMMMMMMMes#.....',
        5: '.....##mMMMxxMMMm##.....',
        6: '....###MMMMMMMMMM###....',
        7: '...#mMMMMMsxxsMMMMMs#...',
        8: '#MMMMMMsxxsMMmMMM#......',
        9: '#mMMMMMsxxsMMMMMm#......',
        10: '#MMMMMMssssMMMMMM#......',
        11: '#mMMMMMssssMMMMMm#......',
        12: '#MMMMMMmmmmMMMMMM#......',
        13: '.##MMMM####MMMM##.......',
        14: '...#MMm#..#mMM#.........',
        15: '...#MM#....#MM#.........',
        16: '...#MM#....#MMM#........',
        17: '...#Ms#.....#mM#........',
        18: '.#MM#.......#MM#........',
        19: '.#MM#.......#MM#........',
        20: '.##mm#.....#mm##........',
        21: '.#####.....#####........',
      }),
    ],
    attack: rows({
      0: '...###......###.........',
      1: '...#MM#....#MM#.........',
      2: '...#MM########MM#.......',
      3: '...#MM#mMMMMm#MM#.......',
      4: '...#Mm#seMMes#mM#.......',
      5: '..#MM##mMxxMm##MM#......',
      6: '.#mM###MMMMMM###Mm#.....',
      7: '.##M#mMMsxxsMMm#M##.....',
      8: '...##MMMmsxxsMMMM##.....',
      9: '.....#mMMmsxxsMMMm#.....',
      10: '.....#MMMMssssMMMM#.....',
      11: '.....#mMMMmmmmMMMm#.....',
      12: '.....##MMMMMMMMMM##.....',
      13: '.......##MM####MM##.....',
      14: '........#MM#..#MM#......',
      15: '........#MM#..#MM#......',
      16: '........#Mm#..#mM#......',
      17: '........#MM#..#MM#......',
      18: '........##m#..#m##......',
      19: '........####..####......',
    }),
  },
  /** Four legs, no fur left. What is under the crust of ash is still burning. */
  cinder_hound: {
    tone: {
      mass: (p) => mix(p.flame, p.rockDeep, 0.55),
    lit: (p) => mix(p.flame, p.citrine, 0.25),
    shade: (p) => mix(p.rockDeep, p.void, 0.3),
    eye: (p) => p.flameCore,
    },
    grid: 24,
    frames: [
      rows({
        7: '.................######.',
        8: '................#mMMMe#.',
        9: '................#mMxxM#.',
        10: '..##########MMMMMM##....',
        11: '#smm##mMMsxxsMMMMMM#....',
        12: '..#mMMsxxsMMmMMm#.......',
        13: '..#mMMsMMsMMMMm#........',
        14: '..#m##mM##MM##s#........',
        15: '..#M#.#M#.#M#...........',
        16: '..#M#.#M#.#M#...........',
        17: '..##..##..##............',
      }),
      rows({
        7: '.................######.',
        8: '................#mMMMe#.',
        9: '................#mMxxM#.',
        10: '..##########MMMMMM##....',
        11: '#smm##mMMsxxsMMMMMM#....',
        12: '..#mMMsxxsMMmMMm#.......',
        13: '..#mMMsMMsMMMMm#........',
        14: '..#m##mM##MM##m#........',
        15: '...#M#M#..#M#M#.........',
        16: '.#M#.#M#M#.#M#..........',
        17: '.##..##.##..##..........',
      }),
    ],
    attack: rows({
      8: '..................#####.',
      9: '.................#mMMe#.',
      10: '.................#Mxxe#.',
      11: '...#########MMMM##......',
      12: '.#smm##mMMsxxsMMMM#.....',
      13: '..#mMMsxxsmMMm#.........',
      14: '..#mMMsMMsMMm#..........',
      15: '..#m##mM##Mm#...........',
      16: '.#M#.#M#.#M#............',
      17: '#M#..#M#.#M#............',
      18: '##...##...##............',
    }),
  },
  /** Plated in broken rock. It does not hide; it simply looks like the floor. */
  shale_crawler: {
    tone: {
      mass: (p) => mix(p.rock, p.rockDeep, 0.35),
    lit: (p) => mix(p.rock, p.chalk, 0.3),
    shade: (p) => mix(p.rockDeep, p.void, 0.35),
    eye: (p) => p.quartz,
    },
    grid: 24,
    frames: [
      rows({
        6: '........########........',
        7: '......##mMMMMMMm##......',
        8: '.....#mMsxxxxsMMm##.....',
        9: '..#MMMsxxxxsMmMMm#......',
        10: '..#MMsxxxxsmMMMMMMe#....',
        11: '..#mMmsMMMmsMMMMMMx#....',
        12: '..#mMMsMMMMsMMMMMe#.....',
        13: '..##mMmsMMMmsMMMm##.....',
        14: '...#s##s##s##s##m#......',
        15: '...#.#..#..#..#.#.......',
      }),
      rows({
        6: '........########........',
        7: '......##mMMMMMMm##......',
        8: '.....#mMsxxxxsMMm##.....',
        9: '..#MMMsxxxxsMmMMm#......',
        10: '..#MMsxxxxsmMMMMMMe#....',
        11: '..#mMmsMMMmsMMMMMMx#....',
        12: '..#mMMsMMMMsMMMMMe#.....',
        13: '..##mMmsMMMmsMMMm##.....',
        14: '...##m##m##m##m##.......',
        15: '.....#..#..#..#.........',
      }),
    ],
    attack: rows({
      2: '....########............',
      3: '..##mMMMMMMm##..........',
      4: '.#mMsxxxxsMMm##.........',
      5: '#mMMsxxxxsMMMMm#........',
      6: '#MMsxxxxsmMMMMMMe#......',
      7: '#mMmsMMMmsMMMMMMx#......',
      8: '##mMmsMMMmsMMMMe#.......',
      9: '.##mMmsMMMmsMMm##.......',
      10: '...##mmMsMMmMMm#........',
      11: '.....##mmMMMMMm#........',
      12: '.......#m##s##s#........',
      13: '........#.#..#.#........',
    }),
  },
  /** Nothing solid at all. A knot of moving air with something bright at the centre. */
  gale_wisp: {
    tone: {
      mass: (p) => mix(p.quartz, p.rockDeep, 0.5),
    lit: (p) => mix(p.quartz, p.chalk, 0.3),
    shade: (p) => mix(p.quartz, p.void, 0.6),
    eye: (p) => p.chalk,
    },
    grid: 24,
    frames: [
      rows({
        4: '...........#######......',
        5: '..........#mMMMMMm#.....',
        6: '..###ss#MMsxxxsMM#......',
        7: '.#ssmmm#MsxeeexsM#......',
        8: '.##mssmmMsxxxsMmM#......',
        9: '..###smMMmMsMmMMMm#.....',
        10: '......##mMMsMMMMMm#.....',
        11: '.......##sMmMMMMm##.....',
        12: '..........########......',
      }),
      rows({
        4: '...........#######......',
        5: '..........#mMMMMMs#.....',
        6: '.###s.#MMsxxxsMM#.......',
        7: '..#ssMm#MsxeeexsM#......',
        8: '##mssmmmMsxxxsMmM#......',
        9: '.###ssmMMmMsMmMMMm#.....',
        10: '......##mMMsMMMMMm#.....',
        11: '.......##sMmMMMMm##.....',
        12: '..........########......',
      }),
    ],
    attack: rows({
      4: '.............######.....',
      5: '............#mMMMm#.....',
      6: '.......##s#MMsxxxsM#....',
      7: '....#ssmm#MsxeeexsMM#...',
      8: '..#MssmmMsxxxsMMMmMM#...',
      9: '..###smMMmMsMmMMMMMs#...',
      10: '....##mMMsMmMMMMm#......',
      11: '......##smMMMMMm##......',
      12: '.........########.......',
    }),
  },
  /** Low and armoured, with one claw far too big for it. Everything it touches frosts. */
  rime_crab: {
    tone: {
      mass: (p) => mix(p.quartz, p.void, 0.4),
    lit: (p) => mix(p.quartz, p.chalk, 0.45),
    shade: (p) => mix(p.quartz, p.void, 0.65),
    eye: (p) => p.chalk,
    },
    grid: 24,
    frames: [
      rows({
        2: '..............##..##....',
        3: '..............#x##x#....',
        4: '..............#xMMx#....',
        5: '..............#MMMM#....',
        6: '..####......#MMM#.......',
        7: '..#xxM#.....#MM#........',
        8: '..#MMM#....#MM#.........',
        9: '..#MMM######MMM#........',
        10: '..##mMMsMMsMMMMMMe#.....',
        11: '...#MMsmMsmMMMMMMx#.....',
        12: '...#mMmsMmsMMMMMMe#.....',
        13: '....##s##s##s##s##......',
        14: '.....#..#..#..#.........',
      }),
      rows({
        2: '..............##..##....',
        3: '..............#x##x#....',
        4: '..............#xMMx#....',
        5: '..............#MMMM#....',
        6: '..####......#MMM#.......',
        7: '..#xxM#.....#MM#........',
        8: '..#MMM#....#MM#.........',
        9: '..#MMM######MMM#........',
        10: '..##mMMsMMsMMMMMMe#.....',
        11: '...#MMsmMsmMMMMMMx#.....',
        12: '...#sMmsMmsMMMMMMe#.....',
        13: '.....##s##s##s##s#......',
        14: '......#..#..#..#........',
      }),
    ],
    attack: rows({
      0: '............###..###....',
      1: '............#xx##xx#....',
      2: '............#xMMMMx#....',
      3: '..............#MMMM#....',
      4: '...............#MM#.....',
      5: '..............#MM#......',
      6: '..####....#MM#..........',
      7: '..#xxM#...#MM#..........',
      8: '..#MMM#..#MM#...........',
      9: '..#MMM######MM#.........',
      10: '...##mMMsMMsMMMMe#......',
      11: '....#MMsmMsmMMMMx#......',
      12: '....#mMmsMmsMMMMe#......',
      13: '.....##m##m##m##........',
      14: '.......#..#..#..........',
    }),
  },
  /** Small, and never where it was. The arc between its horns is the only warning. */
  sparkmite: {
    tone: {
      mass: (p) => mix(p.citrine, p.void, 0.35),
    lit: (p) => mix(p.citrine, p.chalk, 0.35),
    shade: (p) => mix(p.citrine, p.void, 0.6),
    eye: (p) => p.chalk,
    },
    grid: 24,
    frames: [
      rows({
        3: '.......##......##.......',
        4: '.......#x#....#x#.......',
        5: '.......#x#....#x#.......',
        6: '.......##x#..#x##.......',
        7: '........##x##x##........',
        8: '......###mMMMMm###......',
        9: '.....#mMMsxxxxsMMm#.....',
        10: '.....#MMseeeeeesMM#.....',
        11: '.....#mMmsxxxxsmMm#.....',
        12: '......###mMMMMm###......',
        13: '........#ms##sm#........',
        14: '........##....##........',
      }),
      rows({
        3: '.......##......##.......',
        4: '.......#x#....#x#.......',
        5: '.......#x#....#x#.......',
        6: '.......##x#..#x##.......',
        7: '........##x##x##........',
        8: '......###mMMMMm###......',
        9: '.....#mMMsxxxxsMMm#.....',
        10: '.....#MMseeeeeesMM#.....',
        11: '.....#mMmsxxxxsmMm#.....',
        12: '......###mMMMMm###......',
        13: '........#m#..#m#........',
        14: '........##....##........',
      }),
    ],
    attack: rows({
      2: '.......##......##.......',
      3: '.......#x#....#x#.......',
      4: '.......#xx#..#xx#.......',
      5: '........#xx##xx#........',
      6: '.........#xxxxxx#.......',
      7: '.......##xxxxxx##.......',
      8: '......###mMxxMm###......',
      9: '.....#mMMsxxxxsMMm#.....',
      10: '.....#MMseeeeeesMM#.....',
      11: '.....#mMmsxxxxsmMm#.....',
      12: '......###mMMMMm###......',
      13: '........#ms##sm#........',
      14: '........##....##........',
    }),
  },

  // --- demonic --------------------------------------------------------
  //
  // Rot and ember. The family reads as heavy even on the small ones: thick
  // outlines, weight low in the frame, and a lit core showing through.

  /** Small, horned and hunched, arms nearly to the floor. The one that arrives first. */
  imp: {
    tone: {
      mass: (p) => mix(p.venom, p.rockDeep, 0.5),
      lit: (p) => mix(p.venom, p.citrine, 0.3),
      shade: (p) => mix(p.venom, p.void, 0.6),
      eye: (p) => p.ember,
    },
    grid: 24,
    frames: [
      rows({
        4: '.......#x#....#x#.......',
        5: '.......#x######x#.......',
        6: '.......#mMMMMMMm#.......',
        7: '......#mMseeesMm#.......',
        8: '......#MMsxxxsMM#.......',
        9: '......##mmMMMmMm##......',
        10: '....#Ms##MMMMMM##sM#....',
        11: '....#Mm#MMMMMMMM#mM#....',
        12: '....#Mm#MMMMMMMM#mM#....',
        13: '....##s##MMMMMM##s##....',
        14: '....##..#sMMMMm#..##....',
        15: '..........#MMMMMM#......',
        16: '..........#Mm##mM#......',
        17: '..........#MM##MM#......',
        18: '..........##s##s##......',
        19: '..........##....##......',
      }),
      rows({
        4: '.......#x#....#x#.......',
        5: '.......#x######x#.......',
        6: '.......#mMMMMMMm#.......',
        7: '......#mMseeesMm#.......',
        8: '......#MMsxxxsMM#.......',
        9: '......##mmMMMmMm##......',
        10: '....#Ms##MMMMMM##sM#....',
        11: '....#Mm#MMMMMMMM#mM#....',
        12: '....#Mm#MMMMMMMM#mM#....',
        13: '....##s##MMMMMM##s##....',
        14: '....##..#sMMMMm#..##....',
        15: '..........#MMMMMM#......',
        16: '........#MMM##MM#.......',
        17: '......#MM#...#MM#.......',
        18: '......##s#...#s##.......',
        19: '......##.......##.......',
      }),
    ],
    attack: rows({
      4: '........#x#....#x#......',
      5: '........#x######x#......',
      6: '........#mMMMMMMm#......',
      7: '......#MMseeesMm#.####..',
      8: '......#MMsxxxsMM#MMMM#..',
      9: '.....##mMmMMMmm##MM#....',
      10: '....#Ms##MMMMMM###......',
      11: '....#Mm#MMMMMMMM#.......',
      12: '....#Mm#MMMMMMMM#.......',
      13: '....##m##MMMMMM##.......',
      14: '.....##..#mMMMMm#.......',
      15: '.........#MMMMMM#.......',
      16: '.......#MMs##mMM#.......',
      17: '......#MM#..#MM#........',
      18: '......##m#..#m##........',
      19: '......###....###........',
    }),
  },
  /** Tall and thin, with an arm on each side that is mostly edge. */
  flenser: {
    tone: {
      mass: (p) => mix(p.rust, p.void, 0.45),
      lit: (p) => mix(p.rust, p.chalk, 0.3),
      shade: (p) => mix(p.rust, p.void, 0.7),
      eye: (p) => p.flame,
    },
    grid: 24,
    frames: [
      rows({
        3: '.........######.........',
        4: '........#mMMMMm#........',
        5: '........#eMMMMe#........',
        6: '........##ssxx##........',
        7: '......###MmmMMM###......',
        8: '.....#xsMMMssMMMsx#.....',
        9: '....#x##MMMmmMMM##x#....',
        10: '....#x##MMMMMMMM##x#....',
        11: '....##..#MMMMMM#..##....',
        12: '..........#MMMMMM#......',
        13: '..........#mMMMMm#......',
        14: '...........#MMMM#.......',
        15: '...........#MMMM#.......',
        16: '............#Mm#........',
        17: '...........#M##M#.......',
        18: '...........#M##M#.......',
        19: '...........#M##M#.......',
        20: '...........##..##.......',
      }),
      rows({
        3: '.........######.........',
        4: '........#mMMMMm#........',
        5: '........#eMMMMe#........',
        6: '........##ssxx##........',
        7: '.....###.MmmMMM.###.....',
        8: '....#xsM##MssM##Msx#....',
        9: '....#x###MMmmMM###x#....',
        10: '....##..#MMMMMM#..##....',
        11: '..........#MMMMMM#......',
        12: '..........#MMMMMM#......',
        13: '..........#mMMMMm#......',
        14: '...........#MMMM#.......',
        15: '...........#MMMM#.......',
        16: '...........#MMMM#.......',
        17: '...........#MMMM#.......',
        18: '...........#M##M#.......',
        19: '.........##....##.......',
        20: '.........##....##.......',
      }),
    ],
    attack: rows({
      3: '...######...............',
      4: '..#mMMMMm#..............',
      5: '..#eMMMMe#..............',
      6: '..##ssxx##..............',
      7: '.###mmMMMM###.##........',
      8: '#xsMMMssMMMsx#x#........',
      9: '##.#MMmmMMMm#xs#........',
      10: '...#MMMMMMMM##x#........',
      11: '....#MMMMMM#..##........',
      12: '....#MMMMMM#............',
      13: '....#mMMMMm#............',
      14: '.....#MMMM#.............',
      15: '.....#MMMM#.............',
      16: '......#Mm#..............',
      17: '....#M##M#..............',
      18: '..#M#..#M#..............',
      19: '..#M#..#M#..............',
      20: '..##....##..............',
    }),
  },
  /** A sack that got too full. Slow, wide, and lit from the inside. */
  bloat: {
    tone: {
      mass: (p) => mix(p.venom, p.ember, 0.4),
      lit: (p) => mix(p.venom, p.chalk, 0.28),
      shade: (p) => mix(p.venom, p.void, 0.68),
      eye: (p) => p.citrine,
    },
    grid: 24,
    frames: [
      rows({
        3: '.........######.........',
        4: '........#mMMMMm#........',
        5: '.......##sMMMMs##.......',
        6: '.....###MmMMMMmM###.....',
        7: '...#MMMMMsxxxsMMMMm#....',
        8: '...#mMMMsxeeexsMMMm#....',
        9: '...#MMMMsxxxxxsMMMM#....',
        10: '...#mMMMmsxxxsmMMMm#....',
        11: '...#sMMMMmsxsmMMMMm#....',
        12: '.....#mMMMmMmMMMMMm#....',
        13: '......##MMMMMMMMMM##....',
        14: '.........#MM####MM#.....',
        15: '.........#MM#..#MM#.....',
        16: '.........#Mm#..#mM#.....',
        17: '.........##m#..#m##.....',
        18: '.........###....###.....',
      }),
      rows({
        3: '.........######.........',
        4: '........#mMMMMm#........',
        5: '.......##sMMMMs##.......',
        6: '.....###MmMMMMmM###.....',
        7: '...#MMMMMsxxxsMMMMm#....',
        8: '...#mMMMsxeeexsMMMm#....',
        9: '...#MMMMsxxxxxsMMMM#....',
        10: '...#mMMMmsxxxsmMMMm#....',
        11: '...#sMMMMmsxsmMMMMm#....',
        12: '.....#mMMMmMmMMMMMm#....',
        13: '......##MMMMMMMMMM##....',
        14: '.......#MM######MM#.....',
        15: '.......#MM#....#MM#.....',
        16: '.......#Mm#....#mM#.....',
        17: '.......##m#....#m##.....',
        18: '.......###......###.....',
      }),
    ],
    attack: rows({
      2: '........########........',
      3: '......##mMMMMMMm##......',
      4: '.....##sMMMMMMMMs##.....',
      5: '...###MmMMMMMMMMmM###...',
      6: '...#mMMMsxxxxxxsMMMm#...',
      7: '...#mMMsxeeeeeexsMMm#...',
      8: '...#MMMsxeeeeeexsMMM#...',
      9: '...#mMMsxeeeeeexsMMm#...',
      10: '...#sMMmsxxxxxxsmMMm#...',
      11: '.....#mMmMMsxxsmMMMm#...',
      12: '......##MMMmMMmMMM##....',
      13: '.........#MM####MM#.....',
      14: '.........#MM#..#MM#.....',
      15: '.........#Mm#..#mM#.....',
      16: '.........##m#..#m##.....',
      17: '.........###....###.....',
    }),
  },
  /** The biggest thing in the family, and the horns arrive before it does. */
  hornfiend: {
    tone: {
      mass: (p) => mix(p.ember, p.void, 0.45),
      lit: (p) => mix(p.ember, p.flame, 0.45),
      shade: (p) => mix(p.ember, p.void, 0.72),
      eye: (p) => p.flameCore,
    },
    grid: 24,
    frames: [
      rows({
        1: '..#x#..............#x#..',
        2: '..#M#..............#M#..',
        3: '...#M#............#M#...',
        4: '....#MM##########MM#....',
        5: '....#mMMMMMMMMMMm#......',
        6: '....#msseeMMMMeessM#....',
        7: '.....#smMMMMMMMMmm#.....',
        8: '.......#mMsxxxxsMm#.....',
        9: '..#MMMMMMMmMMMMmMMm#....',
        10: '..#MMMMMMMxxxxMMMMMMM#..',
        11: '..#mMMMMMsxxxxsMMMMMm#..',
        12: '..#mMMMMMssxxssMMMMMm#..',
        13: '..#M#mMMMmmMMmmMMMm#M#..',
        14: '..#M#mMMMMMssMMMMMm#M#..',
        15: '..#m#mMMMMMmmMMMMMm#m#..',
        16: '..##.#mMMMMMMMMMMm#.##..',
        17: '.....#mMMssssssMMm#.....',
        18: '.....#mMMm#..#mMMm#.....',
        19: '.....#mMMm#..#mMMm#.....',
        20: '.....#mssm#..#mssm#.....',
        21: '.....#mssm#..#mssm#.....',
        22: '...##mmmm##..##mmmm##...',
        23: '...########..########...',
      }),
      rows({
        1: '..#x#..............#x#..',
        2: '..#M#..............#M#..',
        3: '...#M#............#M#...',
        4: '....#MM##########MM#....',
        5: '....#mMMMMMMMMMMm#......',
        6: '....#msseeMMMMeessM#....',
        7: '.....#smMMMMMMMMmm#.....',
        8: '.......#mMsxxxxsMm#.....',
        9: '..#MMMMMMMmMMMMmMMm#....',
        10: '..#MMMMMMMxxxxMMMMMMM#..',
        11: '..#mMMMMMsxxxxsMMMMMm#..',
        12: '..#mMMMMMssxxssMMMMMm#..',
        13: '..#M#mMMMmmMMmmMMMm#M#..',
        14: '..#M#mMMMMMssMMMMMm#M#..',
        15: '..#m#mMMMMMmmMMMMMm#m#..',
        16: '..##.#mMMMMMMMMMMm#.##..',
        17: '.....#mMMssssssMMm#.....',
        18: '....#mMMm#....#mMMm#....',
        19: '....#mMMm#....#mMMm#....',
        20: '...#mssm#.....#mssm#....',
        21: '...#mssm#.....#mssm#....',
        22: '..##mmmm##...##mmmm##...',
        23: '..########...########...',
      }),
    ],
    attack: rows({
      3: '..#x#..............#x#..',
      4: '...#M##############M#...',
      5: '....#M############M#....',
      6: '.....#Mm########mM#.....',
      7: '......#mMMMMMMMMm#......',
      8: '......#mseeMMeesm#......',
      9: '......#mmsxxxxsmm#......',
      10: '...#MMMMMmMMMMmMMMMM#...',
      11: '..#MMMMMMxxxxMMMMMMM#...',
      12: '..#mMMMMsxxxxsMMMMMm#...',
      13: '..#M#mMMssxxssMMMm#M#...',
      14: '..#M#mMMmmMMmmMMm#M#....',
      15: '..#m#mMMMMMssMMMm#m#....',
      16: '..##.#sMMMMmmMMm#.##....',
      17: '.......#mMMssssMMM#.....',
      18: '.....#MMMs#..#mMMm#.....',
      19: '...#MMMm#....#mMMm#.....',
      20: '..#mssm#.....#mssm#.....',
      21: '..#mssm#.....#mssm#.....',
      22: '.##mmm##....##mmm##.....',
      23: '.#######....#######.....',
    }),
  },
  /** Teeth on legs. There is no head to speak of — the whole front is the bite. */
  maw: {
    tone: {
      mass: (p) => mix(p.rust, p.ember, 0.35),
      lit: (p) => mix(p.rust, p.citrine, 0.35),
      shade: (p) => mix(p.rust, p.void, 0.6),
      eye: (p) => p.flame,
    },
    grid: 24,
    frames: [
      rows({
        5: '...##################...',
        6: '...#mMMMMMMMMMMMMMMm#...',
        7: '...#MsxsxsxsxsxsxsxM#...',
        8: '...#MeMmMmMmMmMmMmeM#...',
        9: '...#MsxsxsxsxsxsxsxM#...',
        10: '...#mmMmMmMmMmMmMmMm#...',
        11: '...##MM##MM##MM##MM##...',
        12: '...#M#..#M#..#M#..#M#...',
        13: '...##....##...##...##...',
      }),
      rows({
        5: '...##################...',
        6: '...#mMMMMMMMMMMMMMMm#...',
        7: '...#MsxsxsxsxsxsxsxM#...',
        8: '...#MeMmMmMmMmMmMmeM#...',
        9: '..#Ms##############sM#..',
        10: '...#mxsxsxsxsxsxsxsm#...',
        11: '...##Mm##Mm##Mm##Mm##...',
        12: '...#M#..#M#..#M#..#M#...',
        13: '....##...##...##...##...',
      }),
    ],
    attack: rows({
      2: '..####################..',
      3: '..#mMMMMMMMMMMMMMMMMm#..',
      4: '..#MsxsxsxsxsxsxsxsxM#..',
      5: '..#MmxxxxxxxxxxxxxxMM#..',
      6: '..#Me##############eM#..',
      7: '..#M#..............#M#..',
      8: '..#M#..............#M#..',
      9: '..#Me##############eM#..',
      10: '..#MMxxxxxxxxxxxxxxMM#..',
      11: '..#MsxsxsxsxsxsxsxsxM#..',
      12: '..#mmMmMmMmMmMmMmMmMm#..',
      13: '...##MM##MM##MM##MM##...',
      14: '...#M#..#M#..#M#..#M#...',
      15: '...##....##...##...##...',
    }),
  },
  /**
   * Not a creature. A stooped figure in a heavy coat with a lantern held out
   * to one side — the only warm thing on any map, which is how you find them.
   * Two frames of the lantern swinging, because a person who never moves at
   * all reads as a prop.
   */
  /**
   * Not a creature. A stooped figure in a heavy coat with a lantern held out
   * to one side — the only warm thing on any map, which is how you find them.
   */
  /** Not a creature. A hooded figure with a lamp on a crook, drawn off the
   *  same person `PORTRAITS.lampwright` draws — the lamp is the read at map
   *  scale, and it is what `LAMPWRIGHT.seen` promises before you see him. */
  lampwright: {
    tone: {
      mass: (p) => mix(p.rust, p.void, 0.72),
      lit: (p) => mix(p.rust, p.void, 0.42),
      shade: (p) => mix(p.void, p.rockDeep, 0.5),
      eye: (p) => p.citrine,
    },
    grid: 24,
    frames: [
      rows({
        2: '..ssss..................',
        3: '...s.s........##........',
        4: '.sssss.......#mm#.......',
        5: '.sooos.....##mmmm##.....',
        6: '.soeos....#MM####ss#....',
        7: '.sooos....#MMe##ess#....',
        8: '.sooos....#MM####ss#....',
        9: '.sooos....#MM####ss#....',
        10: '.sooos.....#Mmmmms#.....',
        11: '.sssss....#MMmmmmss#....',
        12: '.....s...#MMmmmmmsss#...',
        13: '.....s...#MMmsmmmsss#...',
        14: '.....s...#MMmsmmmsss#...',
        15: '......s.#MMMmsmmmmsss#..',
        16: '......s.#MMMmsmmmmsss#..',
        17: '......s.#MMMmmsmmmsss#..',
        18: '......s.#MMMmmsmmmsss#..',
        19: '......s..#MMMmsmmmsss#..',
        20: '......s..#MMmmsmmsss#...',
        21: '......s..############...',
        22: '......s.................',
      }),
      rows({
        2: '..ssss..................',
        3: '....ss........##........',
        4: '..sssss......#mm#.......',
        5: '..sooos....##mmmm##.....',
        6: '..sooos...#MM####ss#....',
        7: '..soeos...#MMe##ess#....',
        8: '..sooos...#MM####ss#....',
        9: '..sooos...#MM####ss#....',
        10: '..sooos....#Mmmmms#.....',
        11: '..sssss...#MMmmmmss#....',
        12: '.....s...#MMmmmmmsss#...',
        13: '.....s...#MMmsmmmsss#...',
        14: '.....s...#MMmsmmmsss#...',
        15: '......s.#MMMmsmmmmsss#..',
        16: '......s.#MMMmsmmmmsss#..',
        17: '......s.#MMMmmsmmmsss#..',
        18: '......s.#MMMmmsmmmsss#..',
        19: '......s..#MMMmsmmmsss#..',
        20: '......s..#MMmmsmmsss#...',
        21: '......s...##########....',
        22: '......s.................',
      }),
    ],
  },
  /** Robed and hooded, arms held out. Whatever it is saying is not for you. */
  chanter: {
    tone: {
      mass: (p) => mix(p.amethyst, p.void, 0.45),
      lit: (p) => mix(p.amethyst, p.chalk, 0.3),
      shade: (p) => mix(p.amethyst, p.void, 0.68),
      eye: (p) => p.venom,
    },
    grid: 24,
    frames: [
      rows({
        3: '.........######.........',
        4: '........#mMMMMm#........',
        5: '........#sseems#........',
        6: '........##xxxx##........',
        7: '......###MMMMMM###......',
        8: '.....#xsMMMMMMMMsx#.....',
        9: '....##MmMsxxxxsMmM##....',
        10: '.....#MMMmsxxsmMMM#.....',
        11: '.....#mMMMmMMmMMMm#.....',
        12: '....#MMMMMMMMMMMMMM#....',
        13: '....#mMMMMMMMMMMMMm#....',
        14: '....#MMMMMMMMMMMMMM#....',
        15: '....#mMMMMMMMMMMMMm#....',
        16: '....#MMMMMMMMMMMMMM#....',
        17: '....#mMMMMMMMMMMMMm#....',
        18: '...##################...',
        19: '....################....',
      }),
      rows({
        3: '.........######.........',
        4: '........#mMMMMm#........',
        5: '........#sseems#........',
        6: '........##xxxx##........',
        7: '.....###.MMMMMM.###.....',
        8: '...#xs###MMMMMM###sx#...',
        9: '....##MMMsxxxxsMMM##....',
        10: '.....#MMMmsxxsmMMM#.....',
        11: '.....#mMMMmMMmMMMm#.....',
        12: '....#MMMMMMMMMMMMMM#....',
        13: '....#mMMMMMMMMMMMMm#....',
        14: '....#MMMMMMMMMMMMMM#....',
        15: '....#mMMMMMMMMMMMMm#....',
        16: '....#MMMMMMMMMMMMMM#....',
        17: '....#mMMMMMMMMMMMMm#....',
        18: '..####################..',
        19: '...##################...',
      }),
    ],
    attack: rows({
      0: '.......#x#....#x#.......',
      1: '.......#x######x#.......',
      2: '.......##xxxxxx##.......',
      3: '.......#x######x#.......',
      4: '.......#x#####x#........',
      5: '.......#x#######........',
      6: '...#x###mMMMMm###x#.....',
      7: '...#xs##sseems##sx#.....',
      8: '....##MMmxxxxmMM##......',
      9: '.....#MMMsxxxxsMMM#.....',
      10: '.....#MMMmsxxsmMMM#.....',
      11: '.....#mMMMmMMmMMMm#.....',
      12: '....#MMMMMMMMMMMMMM#....',
      13: '....#mMMMMMMMMMMMMm#....',
      14: '....#MMMMMMMMMMMMMM#....',
      15: '....#mMMMMMMMMMMMMm#....',
      16: '....#MMMMMMMMMMMMMM#....',
      17: '....#mMMMMMMMMMMMMm#....',
      18: '...##################...',
      19: '....################....',
    }),
  },

  // --- crystal --------------------------------------------------------
  //
  // Bone-light and facets. Nothing in the family has a body in the way the
  // other two do: these are shapes held together, and they read as hollow.

  /** A splinter that has not decided which way is down. */
  shardling: {
    tone: {
      mass: (p) => mix(p.bone, p.quartz, 0.45),
      lit: (p) => mix(p.bone, p.chalk, 0.35),
      shade: (p) => mix(p.bone, p.void, 0.6),
      eye: (p) => p.quartz,
    },
    grid: 24,
    frames: [
      rows({
        4: '...........##...........',
        5: '..........#Mx#..........',
        6: '.........#MMxM#.........',
        7: '........#MsxxsM#........',
        8: '.......#MsxeexsM#.......',
        9: '......#MsxeeexsM#.......',
        10: '.......#msxeexsM#.......',
        11: '........#msxxsm#........',
        12: '.........#mMxm#.........',
        13: '..........#Mm#..........',
        14: '...........##...........',
      }),
      rows({
        3: '...........##...........',
        4: '..........#Mm#..........',
        5: '.........#MMxM#.........',
        6: '........#MsxxsM#........',
        7: '.......#MsxeexsM#.......',
        8: '......#MsxeeexsM#.......',
        9: '.......#msxeexsM#.......',
        10: '........#msxxsm#........',
        11: '.........#mMxm#.........',
        12: '..........#Mx#..........',
        13: '...........##...........',
      }),
    ],
    attack: rows({
      6: '..##....................',
      7: '..#Mx##.................',
      8: '..#MMxxM##..............',
      9: '..#MsxeexxsM##..........',
      10: '..#MsxeeeeexsMM#........',
      11: '..#MsxeexxsM##..........',
      12: '..#MmxxM##..............',
      13: '..#Ms##.................',
      14: '..##....................',
    }),
  },
  /** Grown sideways across the floor on far too many legs. */
  lattice: {
    tone: {
      mass: (p) => mix(p.quartz, p.verdite, 0.35),
      lit: (p) => mix(p.quartz, p.chalk, 0.4),
      shade: (p) => mix(p.quartz, p.void, 0.62),
      eye: (p) => p.chalk,
    },
    grid: 24,
    frames: [
      rows({
        5: '......####....####......',
        6: '.....#mMM#....#MMm#.....',
        7: '....##MsxM####MxsM##....',
        8: '...#mMMseMMMMMMesMMm#...',
        9: '...#MMsxMMMMMMMMxsMM#...',
        10: '...#sMmMMMMMMMMMMmMm#...',
        11: '.....#mMMMMMMMMMMMMm#...',
        12: '....##M##M##M##M##M##...',
        13: '.....#M#.#M#.#M#.#M#....',
        14: '.....##..##..##..##.....',
      }),
      rows({
        5: '......####....####......',
        6: '.....#mMM#....#MMm#.....',
        7: '....##MsxM####MxsM##....',
        8: '...#mMMseMMMMMMesMMm#...',
        9: '...#MMsxMMMMMMMMxsMM#...',
        10: '...#sMmMMMMMMMMMMmMm#...',
        11: '.....#mMMMMMMMMMMMMm#...',
        12: '.....##M##M##M##M##M##..',
        13: '......#M#.#M#.#M#.#M#...',
        14: '......##..##..##..##....',
      }),
    ],
    attack: rows({
      2: '......####....####......',
      3: '.....#mMM#....#MMm#.....',
      4: '....##MsxM####MxsM##....',
      5: '...#mMMseMMMMMMesMMm#...',
      6: '...#MMsxMMMMMMMMxsMM#...',
      7: '...#sMmMMMMMMMMMMmMm#...',
      8: '.....#mMMMMMMMMMMMMm#...',
      9: '....##M##M##M##M##M##...',
      10: '....#M#.#M#.#M#.#M#.....',
      11: '...#M#..#M#.#M#..#M#....',
      12: '..#M#..#M#.#M#..#M#.....',
      13: '.#M#...#M#.#M#..#M#.....',
      14: '.##....##...##...##.....',
    }),
  },
  /** A rock that is hollow, and the hollow is looking back. */
  geode: {
    tone: {
      mass: (p) => mix(p.amethyst, p.rockDeep, 0.45),
      lit: (p) => mix(p.amethyst, p.chalk, 0.35),
      shade: (p) => mix(p.amethyst, p.void, 0.65),
      eye: (p) => p.quartz,
    },
    grid: 24,
    frames: [
      rows({
        4: '........########........',
        5: '......##mMMMMMMm##......',
        6: '.....#mMsxxxxxxsMm#.....',
        7: '...#MMsxeeeeeexsMMm#....',
        8: '...#MMsxeMMMMexsMMM#....',
        9: '...#MMsxeMMMMexsMMM#....',
        10: '...#sMmsxxxxxxsmMMm#....',
        11: '.....#smMMMMMMmMMm#.....',
        12: '.......##MM####MM##.....',
        13: '.........#M#..#M#.......',
        14: '.........#M#..#M#.......',
        15: '.........##....##.......',
      }),
      rows({
        4: '........########........',
        5: '......##mMMMMMMm##......',
        6: '.....#mMsxxxxxxsMm#.....',
        7: '...#MMsxeeeeeexsMMm#....',
        8: '...#MMsxeMMMMexsMMM#....',
        9: '...#MMsxeMMMMexsMMM#....',
        10: '...#sMmsxxxxxxsmMMm#....',
        11: '.....#smMMMMMMmMMm#.....',
        12: '.......##MM####MM##.....',
        13: '........#M#....#M#......',
        14: '........#M#....#M#......',
        15: '........##......##......',
      }),
    ],
    attack: rows({
      3: '........########........',
      4: '......##mMMMMMMm##......',
      5: '.....#mMsxxxxxxsMm#.....',
      6: '...#MMsxeeeeeexsMMm#....',
      7: '...#MMxeeeeeeeexMMM#....',
      8: '...#MMxeeeeeeeexMMM#....',
      9: '...#MMxeeeeeeeexMMM#....',
      10: '...#sMMsxxxxxxsMMMm#....',
      11: '.....#smMMMMMMmMMm#.....',
      12: '.......##MM####MM##.....',
      13: '.........#M#..#M#.......',
      14: '.........#M#..#M#.......',
      15: '.........##....##.......',
    }),
  },
  /** A wedge held a hand above the floor, bright where it should be hollow. */
  prism: {
    tone: {
      mass: (p) => mix(p.quartz, p.amethyst, 0.5),
      lit: (p) => mix(p.chalk, p.quartz, 0.3),
      shade: (p) => mix(p.amethyst, p.void, 0.7),
      eye: (p) => p.chalk,
    },
    grid: 24,
    frames: [
      rows({
        4: '..........####..........',
        5: '.........#MMMM#.........',
        6: '........#MsxxsM#........',
        7: '.......#MsxeexsM#.......',
        8: '......#MsxeeeexsM#......',
        9: '.....#MsxxeeeexxsM#.....',
        10: '.....#MsxxxeexxxsM#.....',
        11: '.....#mmMsxxxxsMmm#.....',
        12: '...##################...',
        13: '....################....',
        15: '.......##########.......',
      }),
      rows({
        3: '..........####..........',
        4: '.........#MMMM#.........',
        5: '........#MsxxsM#........',
        6: '.......#MsxeexsM#.......',
        7: '......#MsxeeeexsM#......',
        8: '.....#MsxxeeeexxsM#.....',
        9: '.....#MsxxxeexxxsM#.....',
        10: '.....#mmMsxxxxsMmm#.....',
        11: '...##################...',
        12: '....################....',
        14: '......############......',
      }),
    ],
    attack: rows({
      3: '..........####..........',
      4: '.........#MeeM#.........',
      5: '........#MexxeM#........',
      6: '.......#MexeexeM#.......',
      7: '......#MexeeeexeM#......',
      8: '.....#MexeeeeeexeM#.....',
      9: '....#MexeeeeeeexeM#.....',
      10: '....#MMexxeeeexxeMM#....',
      11: '....#mMMexxxxxxeMMm#....',
      12: '..####################..',
      13: '....################....',
      15: '........########........',
    }),
  },
  /** A column taller than the hero, walking on the point it stands on. */
  spire: {
    tone: {
      mass: (p) => mix(p.bone, p.amethyst, 0.4),
      lit: (p) => mix(p.bone, p.chalk, 0.45),
      shade: (p) => mix(p.bone, p.void, 0.66),
      eye: (p) => p.citrine,
    },
    grid: 24,
    frames: [
      rows({
        2: '...........##...........',
        3: '..........#Mx#..........',
        4: '.........#MxM#..........',
        5: '.........#MsxM#.........',
        6: '........#MeexM#.........',
        7: '........#MMsxxM#........',
        8: '.......#MsxxxsM#........',
        9: '......#mMmxxxmMm#.......',
        10: '......#MMsxxxxsMM#......',
        11: '.....#mMMxxxxxmMm#......',
        12: '.....#MMsxxxxxxsMM#.....',
        13: '....#mMMmxxxxxMmMm#.....',
        14: '....#MMsxxxxxxxxsMM#....',
        15: '....#mMmMMMMMMMMmMm#....',
        16: '...##################...',
        17: '......##MM####MM##......',
        18: '.......#M#....#M#.......',
        19: '.......##......##.......',
      }),
      rows({
        2: '...........##...........',
        3: '..........#Mx#..........',
        4: '.........#MxM#..........',
        5: '.........#MsxM#.........',
        6: '........#MeexM#.........',
        7: '........#MMsxxM#........',
        8: '.......#MsxxxsM#........',
        9: '......#mMmxxxmMm#.......',
        10: '......#MMsxxxxsMM#......',
        11: '.....#mMMxxxxxmMm#......',
        12: '.....#MMsxxxxxxsMM#.....',
        13: '....#mMMmxxxxxMmMm#.....',
        14: '....#MMsxxxxxxxxsMM#....',
        15: '....#mMmMMMMMMMMmMm#....',
        16: '...##################...',
        17: '.......##MM##MM##.......',
        18: '........#M#..#M#........',
        19: '........##....##........',
      }),
    ],
    attack: rows({
      2: '...............##.......',
      3: '..............#Mx#......',
      4: '.............#MxM#......',
      5: '............#MsxM#......',
      6: '...........#MeexM#......',
      7: '..........#MMsxxM#......',
      8: '.........#MsxxxsM#......',
      9: '........#mMmxxxmMm#.....',
      10: '.......#MMsxxxxsMM#.....',
      11: '......#mMMxxxxxmMm#.....',
      12: '.....#MMsxxxxxxsMM#.....',
      13: '....#mMMmxxxxxMmMm#.....',
      14: '....#MMsxxxxxxxxsMM#....',
      15: '...#mMMmMMMMMMMMmm#.....',
      16: '...##################...',
      17: '...##MM####MM##.........',
      18: '....#M#....#M#..........',
      19: '....##......##..........',
    }),
  },
  /** A ring of shards around a core, turning. You hear it before you see it. */
  chime: {
    tone: {
      mass: (p) => mix(p.citrine, p.quartz, 0.5),
      lit: (p) => mix(p.citrine, p.chalk, 0.4),
      shade: (p) => mix(p.citrine, p.void, 0.58),
      eye: (p) => p.chalk,
    },
    grid: 24,
    frames: [
      rows({
        4: '.......#x#....#x#.......',
        5: '.......#MM#..#MM#.......',
        6: '.......#MMM##MMM#.......',
        7: '......##mMMMMMMm##......',
        8: '.....#mMsxeeexsMm#......',
        9: '.....#MMsxeeexsMM#......',
        10: '.....#mMsxeeexsMm#......',
        11: '......##mMMMMMmm##......',
        12: '.......#MMM##MMM#.......',
        13: '.......#MM#..#MM#.......',
        14: '.......#x#....#x#.......',
      }),
      rows({
        3: '.....#x#........#x#.....',
        4: '......#MM#....#MM#......',
        5: '.......#MM#..#MM#.......',
        6: '........##mMMMMm##......',
        7: '......#MMsxeeexsMm#.....',
        8: '....#MMsxeeeeexsMM#.....',
        9: '......#sMsxeeexsMm#.....',
        10: '........##mMMMMm##......',
        11: '.......#MM#..#MM#.......',
        12: '......#MM#....#MM#......',
        13: '.....#x#........#x#.....',
      }),
    ],
    attack: rows({
      2: '.......#x#....#x#.......',
      3: '.......#xx#..#xx#.......',
      4: '.......#xxx##xxx#.......',
      5: '.......#MMxxxxMM#.......',
      6: '.......#MMMxxMMM#.......',
      7: '......##mMMMMMMm##......',
      8: '.....#mMsxeeexsMm#......',
      9: '.....#MMxeeeeexMM#......',
      10: '.....#mMsxeeexsMm#......',
      11: '......##mMMMMMmm##......',
      12: '.......#MMMxxMMM#.......',
      13: '.......#MMxxxxMM#.......',
      14: '.......#xxx##xxx#.......',
      15: '.......#xx#..#xx#.......',
      16: '.......#x#....#x#.......',
    }),
  },
};

/** The frames alone, for the harness that only asks whether they are well formed. */
export const MONSTER_FRAMES: Record<string, string[][]> = Object.fromEntries(
  Object.entries(BEASTIARY).map(([id, art]) => [id, art.frames])
);

/** Common, magic, rare. The accent ink and the halo both key off this. */
export type MonsterRank = 'common' | 'magic' | 'rare';

export const HALO: Record<MonsterRank, string | null> = {
  common: null,
  magic: 'b',
  rare: 'o',
};

/** Rings per rank, so the border itself says which is the rarer of the two. */
export const HALO_RANK: Record<MonsterRank, number> = { common: 0, magic: 1, rare: 2 };

/**
 * A one-pixel ring around whatever the creature already is, so the border
 * follows its silhouette rather than boxing it. Grown outward only: a halo
 * that ate a pixel of the body would thin every leg it touched.
 */
export function haloed(frame: string[], ink: string | null, rings = 1): string[] {
  if (!ink) return frame;
  let out = frame;
  for (let ring = 0; ring < rings; ring++) {
    const grown = out;
    const lit = (x: number, y: number) => (grown[y]?.[x] ?? '.') !== '.';
    out = grown.map((row, y) =>
      row
        .split('')
        .map((ch, x) => {
          if (ch !== '.') return ch;
          const near =
            lit(x - 1, y) || lit(x + 1, y) || lit(x, y - 1) || lit(x, y + 1);
          return near ? ink : ch;
        })
        .join('')
    );
  }
  return out;
}

/**
 * How many rings make the ONE the 24 grid was drawn with. A ring is in art
 * pixels, so a single one on a 256 grid is a third of a device pixel on screen:
 * it aliases in and out along the silhouette and reads as a broken line.
 */
export const haloRings = (grid: number): number => Math.max(1, Math.round(grid / 24));
