/**
 * The figure under the armour: a person in a shirt and trousers, facing right.
 * It has to read on its own, because a fresh character wears nothing.
 *
 * The grip is at (17, 14) and `POSES[..].hand` moves it. Every weapon is drawn
 * against that one point.
 *
 * The walk is contact, pass, contact, pass. A pass has the legs TOGETHER with
 * one foot off the ground and the whole figure a pixel higher — without it two
 * planted frames alternate and the figure reads as doing the splits on the
 * spot. `POSES` lifts the armour by that pixel so the two stay together.
 */
import type { PoseId } from './pose';

/**
 * `#` ink · `s` skin · `e` eye · `h` hair · `t` shirt · `T` shirt shadow
 * `l` trouser · `L` trouser shadow · `b` bare foot
 */
export const BODY: Record<PoseId, string[]> = {
  // Contact: weight landing, the near leg leading and lit.
  walk0: [
    '........................',
    '........................',
    '........................',
    '........######..........',
    '.......#hhhhhh#.........',
    '.......#hhhhhh#.........',
    '.......#hhssse#.........',
    '.......#hsssse#.........',
    '.......#ssssss#.........',
    '........#ssss#..........',
    '........#sss#...........',
    '.....##ttttttt##........',
    '...#ttTtttttttTttt#.....',
    '...#ssTtttttttTttt#.....',
    '...#ssTtttttttTsss#.....',
    '.....#TtttttttT#........',
    '.....#TtttttttT#........',
    '....#lllllllllll#.......',
    '....#llL#####Lll#.......',
    '....#llL#####Lll#.......',
    '....#lll.....LLL#.......',
    '....#lll.....LLL#.......',
    '....#bbb.....bbb#.......',
    '....####.....####.......',
  ],
  // Pass: legs together, rear foot off the ground, everything a pixel up.
  walk1: [
    '........................',
    '........................',
    '........######..........',
    '.......#hhhhhh#.........',
    '.......#hhhhhh#.........',
    '.......#hhssse#.........',
    '.......#hsssse#.........',
    '.......#ssssss#.........',
    '........#ssss#..........',
    '........#sss#...........',
    '.....##ttttttt##........',
    '...#ttTtttttttTttt#.....',
    '...#ssTtttttttTttt#.....',
    '...#ssTtttttttTsss#.....',
    '.....#TtttttttT#........',
    '.....#TtttttttT#........',
    '.....#lllllllll#........',
    '.....#lll##lll#.........',
    '.....#lll##lll#.........',
    '.....#lll##lll#.........',
    '.....#lll##lll#.........',
    '.....#lll##bbb#.........',
    '.....#bbb######.........',
    '.....#####..............',
  ],
  // Contact again, the other leg leading: the shading is what says which.
  walk2: [
    '........................',
    '........................',
    '........................',
    '........######..........',
    '.......#hhhhhh#.........',
    '.......#hhhhhh#.........',
    '.......#hhssse#.........',
    '.......#hsssse#.........',
    '.......#ssssss#.........',
    '........#ssss#..........',
    '........#sss#...........',
    '.....##ttttttt##........',
    '...#ttTtttttttTttt#.....',
    '...#ssTtttttttTttt#.....',
    '...#ssTtttttttTsss#.....',
    '.....#TtttttttT#........',
    '.....#TtttttttT#........',
    '....#lllllllllll#.......',
    '....#llL#####Lll#.......',
    '....#llL#####Lll#.......',
    '....#LLL.....lll#.......',
    '....#LLL.....lll#.......',
    '....#bbb.....bbb#.......',
    '....####.....####.......',
  ],
  // Pass, the other foot up.
  walk3: [
    '........................',
    '........................',
    '........######..........',
    '.......#hhhhhh#.........',
    '.......#hhhhhh#.........',
    '.......#hhssse#.........',
    '.......#hsssse#.........',
    '.......#ssssss#.........',
    '........#ssss#..........',
    '........#sss#...........',
    '.....##ttttttt##........',
    '...#ttTtttttttTttt#.....',
    '...#ssTtttttttTttt#.....',
    '...#ssTtttttttTsss#.....',
    '.....#TtttttttT#........',
    '.....#TtttttttT#........',
    '.....#lllllllll#........',
    '.....#lll##lll#.........',
    '.....#lll##lll#.........',
    '.....#lll##lll#.........',
    '.....#lll##lll#.........',
    '.....#bbb##lll#.........',
    '.....######bbb#.........',
    '..........#####.........',
  ],
  // The strike: shoulders squared, weight driven through, arm at full reach.
  // The sim deals its damage the instant this pose starts, so this is the
  // extreme rather than a wind-up toward one.
  attack0: [
    '........................',
    '........................',
    '........................',
    '........######..........',
    '.......#hhhhhh#.........',
    '.......#hhhhhh#.........',
    '.......#hhssse#.........',
    '.......#hsssse#.........',
    '.......#ssssss#.........',
    '........#ssss#..........',
    '........#sss#...........',
    '.....#ttttttttt#........',
    '...#ttTtttttttTttt#.....',
    '...#ssTtttttttTtttt#....',
    '...#ssTtttttttTssss#....',
    '.....#TtttttttT#........',
    '.....#TtttttttT#........',
    '....#lllllllllll#.......',
    '....#llL#####Lll#.......',
    '....#llL#####Lll#.......',
    '....#lll.....LLL#.......',
    '....#lll.....LLL#.......',
    '....#bbb.....bbb#.......',
    '....####.....####.......',
  ],
  // The follow-through: the arm carried down past the swing, weight settling.
  attack1: [
    '........................',
    '........................',
    '........................',
    '........######..........',
    '.......#hhhhhh#.........',
    '.......#hhhhhh#.........',
    '.......#hhssse#.........',
    '.......#hsssse#.........',
    '.......#ssssss#.........',
    '........#ssss#..........',
    '........#sss#...........',
    '.....##ttttttt##........',
    '...#ttTtttttttTtt#......',
    '...#ssTtttttttTtt#......',
    '...#ssTtttttttTtt#......',
    '.....#TtttttttTsss#.....',
    '.....#TtttttttT#........',
    '....#lllllllllll#.......',
    '....#llL#####Lll#.......',
    '....#llL#####Lll#.......',
    '....#LLL.....lll#.......',
    '....#LLL.....lll#.......',
    '....#bbb.....bbb#.......',
    '....####.....####.......',
  ],
  // Braced back on the rear foot with the arm out in FRONT, not straight up.
  // A raised arm reads as a signal; an extended one reads as aiming.
  cast0: [
    '........................',
    '........................',
    '........................',
    '........................',
    '........######..........',
    '.......#hhhhhh#.........',
    '.......#hhhhhh#.........',
    '.......#hhssse#.........',
    '.......#hsssse#...####..',
    '.......#ssssss##sss#....',
    '........#ssss#sssss#....',
    '........#sss#ss#........',
    '.....##ttttttt##........',
    '...#ttTtttttttT#........',
    '...#ssTtttttttT#........',
    '.....#TtttttttT#........',
    '.....#TtttttttT#........',
    '....#lllllllllll#.......',
    '....#llL#####Lll#.......',
    '....#llL#####Lll#.......',
    '....#lll.....LLL#.......',
    '....#lll.....LLL#.......',
    '....#bbb.....bbb#.......',
    '....####.....####.......',
  ],
  // The hand coming down off the release, the weight coming back over the feet.
  cast1: [
    '........................',
    '........................',
    '........................',
    '........................',
    '........######..........',
    '.......#hhhhhh#.........',
    '.......#hhhhhh#.........',
    '.......#hhssse#.........',
    '.......#hsssse#.........',
    '.......#ssssss#.........',
    '........#ssss#.####.....',
    '........#sss#.#sss#.....',
    '.....##ttttttt#sss#.....',
    '...#ttTtttttttTss#......',
    '...#ssTtttttttTs#.......',
    '.....#TtttttttT#........',
    '.....#TtttttttT#........',
    '....#lllllllllll#.......',
    '....#llL#####Lll#.......',
    '....#llL#####Lll#.......',
    '....#LLL.....lll#.......',
    '....#LLL.....lll#.......',
    '....#bbb.....bbb#.......',
    '....####.....####.......',
  ],
};
