/**
 * Written by `tools/art/portrait.mts`. Do not edit by hand.
 *
 * Effect art, drawn in the WORLD rather than in a panel: cropped to its own
 * ink and squared up, so the picture's edges are the effect's edges and the
 * renderer can pin it by them. One frame each, carrying their own
 * colours, and only Pixi draws one — canvas2d has no sprites.
 */
export type GeneratedVfx = {
  grid: number;
  rows: string[];
  key: Record<string, string>;
};

export const VFX_ART: Record<string, GeneratedVfx> = {
  arrow: {
    grid: 48,
    rows: [
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      'AABBBBAB........................................',
      '.CDECFBCD...............................BEADD...',
      '.CCCFCCACG...............................HIIJEFF',
      '..BGBBGBGGAEEEEEEEEEEEEEEEEEEEEEEEEEEFEFFBBJIDA.',
      '.ECACCBDDC..............................ABFFD...',
      'AFBAABFE........................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
    ],
    key: {"A":"#101318","B":"#07080a","C":"#566270","D":"#3d4650","E":"#2a313a","F":"#1b2027","G":"#0b1a0e","H":"#2a1c0c","I":"#77828e","J":"#9aa3a8"},
  },
  storm: {
    grid: 64,
    rows: [
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '.............................AABBAA.............................',
      '...........................AABBBBAAAA...........................',
      '..........................AABBBCCCCBBD..........................',
      '.........................AABBBBCCCCCBAA.........................',
      '......................DEDAABBBCCCFFFCCBD........................',
      '....................DEDDDDACCBCCCCCFFCBB........................',
      '...................DEDDDDDABCCBCCCCCCCBAADDD....................',
      '...................EEEDADDDBCCBBCCCCCCBADAAAAA..................',
      '.................DEEEDDDDDABCCBBBCCCCCAAAABBAABB................',
      '................DDEEEDDDDDDABBBBBCCCCBDDBCBBBCCB................',
      '...............DDDEEEEDDDDDABBBABBBBBAEABCCCCCCC................',
      '..............ADDEEDEEEDDDDADBCBBCBAAEDABCCCCFCCE...............',
      '..............DDDDEEEEEEDECADAAAAAAAAEDABBCCCGFCA...............',
      '.............DDEEEDDAAADDEDDDDADAAAADEDDBBCCCCCBBD..............',
      '.............EDDEDADACAAEEDDDDDDDDADDEDABCCCBCCBBD..............',
      '.........DEEEEDDDDDDAAAAEEDDDDDDDDDDEEDABBBBBBBDAAAAA...........',
      '........DEEDEEDEDDDAAABAEEEEEDDDDEEEEHDDACCCBDDDABBBAAD.........',
      '.......DDDDDDEEEEDDDAABAEEEEEEEEEEDEDEEEAAADDDAABCCCBBAD........',
      '......DDAAABBDHEEEDDDAADHHDDHEEEDAAABBAADAADAAAABCCCCCBB........',
      '......EDABCCCDDDEEEDDDDDHEEEEDEDAAABCCBBADADAAAABCCFFCBBD.......',
      '.....DEDABCCFDAEEEEEEDAAAEEEEEEABBBBBCCFCADDAAABCCCCFCCBA.......',
      '.....EDDDABBBAAEEDAABBBCBBBBEEDABBBCCCCCCBADAAABBCCCCCBBAD......',
      '...EEEDDAAAAAADHDDAABBCCCCCCBADAABCCCCCCCBAADDCABBBCCBBBAE......',
      '..DDDEEDDDAAAEEEDDDABCCCCFFCCBDDBBBCCCCCCBBBBDAACABCBBBAED......',
      '.EDDDEEEDEEEEEDEDDDDBBBCCFFFCBADBBBBBBBCBBBCCBAEBBBBBAAADA......',
      '.EDDEEEEEEEEDDEEDDDDDBBCCIFFCBBAAAAABBBBCBBCCICAAAAAAABBBBBD....',
      'DDDDEEEEEHHHHEEEDDDDABBCCCCCCCBBABAAABBBBBCCCFCBAAAAABBBCFCAA...',
      'EDDDEHEDDDHEEEEEDDDCABBCCCCCBBBBAAABABBBBBBBCCCBEAABAABBCFFBAD..',
      'DDEEEDDAADDDDEEDDDEDADBCCCCCCBBBDAAAAAAABAABBBBBEAADAABCCCCBAD..',
      'DEEEDDAABBCAAEEHDDDCAAABCBBBCBBAAAAAEEDAADDAAAAAADDDDAAABBBAAD..',
      '.EEDDDAABBBCBEEEDDDDAAAABBBBCBAADBAEEAAAABAEAABDADABBCCABBAADAA.',
      '.EEDDDAABBBCIAEEDDDDAAAAABBBBBAADAEDDABBCCCCDAAEDABBCCGCAAAADABA',
      'EEEDDDDACACCIBEEDDDDDDABAABBBBAAEHEDAABBCCFCBDAEDABBCIFCEDDDDBBA',
      'EEEDEDDABBBCCAEEDDDDDDAAAAAAAAAAHDDDAAACCFFFCDEEDABBCCCCDDAEABBA',
      'EEDDEDDDAABBBADEEDDDDDDDAAAAAADAHDDDBBBCCCFCBDEEDBABBCCCAEBCADAA',
      'EEEEEDDDAAAAAADHEDDDDDDDDDAADDDDEDDDAABBCCCBAAHEDADBBCCBAEBCBDAA',
      'EEEEEDDDAAABAADDEEDDDDDDDDDDDDDEEDDDDAACCBBBBAHEDDDAABBBDEBBBDAA',
      '.EDEEEDDDDDDDDDEHEEEDDDDDDDDDEEEEEDDDDDDBBBAADEEDDDADDDDEEAAADAD',
      '..DDEEDEDDDDDDEEEEEEEEDDDDDEDEHEEEEDDDDDADADDEEEDDDDDDDDEEDADDDE',
      '....DEEEEDDDEEEEEEEDEEEEEEEEEEEHEEEEDDDDDDDDEDEEEEDDDDDEEEDDDDD.',
      '.....EEEEEEEEEHEEAEEEEEEEEEEEEHHEEEEEEEDDDDDEHJEDDEEEEEEHEDDEE..',
      '......DEEEEEEEDADAAAEEEEEDEHEEEKEEEEEEEDEEEDJEJJEEEHEED.DDEE....',
      '........EDEE....EDADDDH....EEEKKLEEEEEEEEEEH.......HHD..........',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
    ],
    key: {"A":"#3d4650","B":"#566270","C":"#77828e","D":"#2a313a","E":"#1b2027","F":"#e8eef2","G":"#c6ccd2","H":"#101318","I":"#9aa3a8","J":"#6e4e22","K":"#8a6a34","L":"#f5c24a"},
  },
  poison_pool: {
    grid: 48,
    rows: [
      '................................................',
      '..................................ABA...........',
      '......CD.........................CEEFGA.........',
      '......HI........................ADEEEGJ.........',
      '......CK.......................LGEEGGBJ.......GK',
      '......GK............LMMMMMMJ...BKECGKBJ.........',
      '................NBGCEEEEEEEEOCPKEFKBAL..........',
      '...............ADKKGEEEEEEEEEQAEEFKMM...........',
      '...ADGBK......BCGCROJGKGGGGGGFCCIEEBA....IM.....',
      '..PCFFDK.....ACEGCHFGCEEEEEEEFGGGEECJ....L......',
      '..JKEEHFL...JCEEAGCIAEHHHHHHHGEEEGKCFJL.........',
      '..GGEEEFJA.BIEEEGAGGHHHHHHHHHHHEEEGGEGJ.........',
      '..BGGGGGSSKEEEGGEEHHHHHHHHHHHHHHHHEEGEOJD.LGKKP.',
      '..BJGGGGEEEEEEEEHHHHHHHHHHHHHHHHHHHEEKIDAAGCCHC.',
      '...LABABGGEEEKEHHHHHHHHHHHHHHHHHHHHHEEKEEEFGBGJ.',
      '....MMMMBGEEKEHHHHHHHHHHHHHHHHHHHHHHHEKEEEFJABL.',
      '........JGEEEEHHHHHHHHHHHHHHHHHHHHHHHEEGEFAM....',
      '........JKEEEHHHHHHHHHHHHHHHHHHHHHHHHHEGEFG.....',
      '.......PKEEEHHHHHHHHHHHHHHHHHHHHHHHHHHHGEFG.....',
      '.......MEEECHHHHHHHHHHHHHHHHHHHHHHHHHHHGEFJ.....',
      '......LGEEEGHHHHHHHHHHHHHHHHHHHHHHHHHHHGEEGL....',
      '......LKEEEGHHHHHHHHHHHHHHHHHHHHHHHHHHHGEECM....',
      '..ADLGCCEEECHHHHHHHHHHHHHHHHHHHHHHHHHHHCEEEM....',
      '.AKFGCGGCEEEHHHHHHHHHHHHHHHHHHHHHHHHHHHEEEECC...',
      'MBGGJBAAGKEEHHHHHHHHHHHHHHHHHHHHHHHHHHHEEEEFFN..',
      '.MBBM...AKEEEHHHHHHHHHHHHHHHHHHHHHHHHHGEEEEEEGA.',
      '..AM....LGKEEEHHHHHHHHHHHHHHHHHHHHHHHCKEEEEEEGL.',
      '........MJGEEEFHHHHHHHHHHHHHHHHHHHHHHEEEEEEEEBM.',
      '.........MGEEEEHHHHHHHHHHHHHHHHHHHHHCEEEEEEEEBA.',
      '.........AEEEEEEFHHHHHHHHHHHHHHHHHHEEEEEEEEEEEK.',
      '......AMMGEEEEEEEEHHHHHHHHHHHHHHHFEEEEEGCCEEEEEA',
      '...PDIEEEEEEEEEEEEEEFFHHHHHHHFFEEEEECGGGGKGCEEEK',
      '..PKFEEEEEEEEEEEEEEEEEEFFFFFHEEEEEECGGGABAGGCEEB',
      '..JEEEEEEEEECCEEEEEEEEEEEEEEEEEEEEEGJMM...MBGKGG',
      '.NGEEEEEEEECGGCCEEEEEEEEEEEEEEEEEESJM......ABGGB',
      '.MKCEEEEEEGGMABGEEECCKKCEEEEEEEEEEOJ........MBBM',
      '.MGGEEEEFFJLMMMGEECGKGGGEEEEEEEEEEEKA........MM.',
      '..BGCIEECGA...JGFEGBBAGJGEEEEEEEEEEFC...........',
      '..BGGKKKGG....JGICJMMMBMGEEEEEEEEEEEFL..........',
      '..LLBGGGAA....BGGG......GEEEEEEEEEEEFL..........',
      '...MAABAM.....MAAA......GEEEEEEEEEEEFL..........',
      '........................GCEEEEEEEEEFGM..........',
      '........................BGKEEEEEEEEKGL..........',
      '.GED....................MGGGDFEFFHCGB...........',
      '.KEJ....................LBGGGKCCCKKGA...........',
      '.........................MAAJGGGGBBA............',
      '..........................LAAJMABAA.............',
      '................................................',
    ],
    key: {"A":"#0b1a0e","B":"#16301a","C":"#5f9433","D":"#77828e","E":"#9ccb4e","F":"#ffe9a8","G":"#325e24","H":"#c3e27a","I":"#7cb03d","J":"#22471f","K":"#47792b","L":"#101318","M":"#07080a","N":"#1b2027","O":"#e8eef2","P":"#2a1c0c","Q":"#9aa3a8","R":"#ffffff","S":"#c6ccd2"},
  },
  poison_drop: {
    grid: 48,
    rows: [
      '.........................A......................',
      '.........................A......................',
      '.........................A......................',
      '.........................A......................',
      '.........................A......................',
      '.........................A......................',
      '.........................A......................',
      '.........................A......................',
      '.........................A......................',
      '.........................A......................',
      '.........................B......................',
      '.........................C......................',
      '........................AC......................',
      '........................CDB.....................',
      '........................EFB.....................',
      '.......................BCGB.....................',
      '.......................AHGB.....................',
      '.......................ACHCB....................',
      '.......................ACHAA....................',
      '.......................IJKHCE...................',
      '.......................DLCCCA...................',
      '.......................FGCCCCA..................',
      '......................AGCCCCGA..................',
      '.....................GGGCCCCAC..................',
      '....................BCMGGCCCCC..................',
      '...................EHGGCCECCCC..................',
      '..................AGFGGGECCCCCA.................',
      '.................AHFEGECCCCCCCHB................',
      '................BGGFFCGGCCCCCCGCA...............',
      '...............NCFOOFGGGCCCCCCCCA...............',
      '...............CPDOFGGCCCCCCCCCACA..............',
      '..............CCGFFGGGGCCCCCCHCKAC..............',
      '..............CCGFGGCGCCCCCCCCCCPG..............',
      '..............CCCGGCECCCCCCCCCCCCGB.............',
      '.............EGEECCCCCACHCCCCCCCCQB.............',
      '.............EGCCCCCEECCCCECCGCCCCB.............',
      '.............BGCCCCCECCCCCCCCCCCCCB.............',
      '..............ACCCCCACCCCCCECCCCCGH.............',
      '..............ACCCCCCCCCCCCCCCCCCGE.............',
      '..............AEHCCCCCCECCCCCCCCCCC.............',
      '...............CCCCCDCCCCCCCCCCCCH..............',
      '...............AECCCCCCCCCCCCECCCB..............',
      '................EICIIIIAECCCCECKA...........G...',
      '....QB...........BRCCCIKCCCCCCIE................',
      '..................ACKACCCCCAKAA.................',
      '.........AAAAAK.................................',
      '........HPKCHCA.................................',
      '...B....KOGAAAA.................................',
    ],
    key: {"A":"#07080a","B":"#101318","C":"#16301a","D":"#3d4650","E":"#0b1a0e","F":"#c3e27a","G":"#5f9433","H":"#22471f","I":"#566270","J":"#9aa3a8","K":"#47792b","L":"#9ccb4e","M":"#e8eef2","N":"#1b2027","O":"#ffffff","P":"#325e24","Q":"#7cb03d","R":"#2a313a"},
  },
};
