/**
 * Written by `tools/art/portrait.mts`. Do not edit by hand.
 *
 * Effect art, drawn in the WORLD rather than in a panel: cropped to its own
 * ink and squared up, so the picture's edges are the effect's edges and the
 * renderer can pin it by them. One frame each, carrying their own
 * colours, and only Pixi draws one — canvas2d has no sprites.
 */
export type GeneratedVfx = {
  grid: number;
  rows: string[];
  key: Record<string, string>;
};

export const VFX_ART: Record<string, GeneratedVfx> = {
  arrow: {
    grid: 48,
    rows: [
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      'ABBBBBB.CBCB.DE.................................',
      'AFGHBIJB.BFH..D...........................BC....',
      '.KJJFKKFB.BJB.D.....D.....................IGBB..',
      '..BKKBBKBBBBBCCEDCBBDDKACCCCACACCCCBCCACAALMIIBC',
      '...BKKBKKBBKKBBBEDDHHNDBAAAAAAAAAAAAAAAAAAMMIGGG',
      '..KBHKBHJB.BJB.ODB.BKKDEKKKKKKKKKKKKKKKKKKMGFFBB',
      '.BHGHKFFC.BHBDDD..E...OD..................FHBC..',
      'AGIHBJHC.BGHODOE..........................KB....',
      'ACBCACC.ACCADD..................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
    ],
    key: {"A":"#1b2027","B":"#101318","C":"#2a1c0c","D":"#f5c24a","E":"#ffe9a8","F":"#566270","G":"#77828e","H":"#3d4650","I":"#9aa3a8","J":"#2a313a","K":"#07080a","L":"#e8eef2","M":"#c6ccd2","N":"#ffffff","O":"#d9a441"},
  },
  storm: {
    grid: 64,
    rows: [
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '.............................AABBAA.............................',
      '...........................AABBBBAAAA...........................',
      '..........................AABBBCCCCBBD..........................',
      '.........................AABBBBCCCCCBAA.........................',
      '......................DEDAABBBCCCFFFCCBD........................',
      '....................DEDDDDACCBCCCCCFFCBB........................',
      '...................DEDDDDDABCCBCCCCCCCBAADDD....................',
      '...................EEEDADDDBCCBBCCCCCCBADAAAAA..................',
      '.................DEEEDDDDDABCCBBBCCCCCAAAABBAABB................',
      '................DDEEEDDDDDDABBBBBCCCCBDDBCBBBCCB................',
      '...............DDDEEEEDDDDDABBBABBBBBAEABCCCCCCC................',
      '..............ADDEEDEEEDDDDADBCBBCBAAEDABCCCCFCCE...............',
      '..............DDDDEEEEEEDECADAAAAAAAAEDABBCCCGFCA...............',
      '.............DDEEEDDAAADDEDDDDADAAAADEDDBBCCCCCBBD..............',
      '.............EDDEDADACAAEEDDDDDDDDADDEDABCCCBCCBBD..............',
      '.........DEEEEDDDDDDAAAAEEDDDDDDDDDDEEDABBBBBBBDAAAAA...........',
      '........DEEDEEDEDDDAAABAEEEEEDDDDEEEEHDDACCCBDDDABBBAAD.........',
      '.......DDDDDDEEEEDDDAABAEEEEEEEEEEDEDEEEAAADDDAABCCCBBAD........',
      '......DDAAABBDHEEEDDDAADHHDDHEEEDAAABBAADAADAAAABCCCCCBB........',
      '......EDABCCCDDDEEEDDDDDHEEEEDEDAAABCCBBADADAAAABCCFFCBBD.......',
      '.....DEDABCCFDAEEEEEEDAAAEEEEEEABBBBBCCFCADDAAABCCCCFCCBA.......',
      '.....EDDDABBBAAEEDAABBBCBBBBEEDABBBCCCCCCBADAAABBCCCCCBBAD......',
      '...EEEDDAAAAAADHDDAABBCCCCCCBADAABCCCCCCCBAADDCABBBCCBBBAE......',
      '..DDDEEDDDAAAEEEDDDABCCCCFFCCBDDBBBCCCCCCBBBBDAACABCBBBAED......',
      '.EDDDEEEDEEEEEDEDDDDBBBCCFFFCBADBBBBBBBCBBBCCBAEBBBBBAAADA......',
      '.EDDEEEEEEEEDDEEDDDDDBBCCIFFCBBAAAAABBBBCBBCCICAAAAAAABBBBBD....',
      'DDDDEEEEEHHHHEEEDDDDABBCCCCCCCBBABAAABBBBBCCCFCBAAAAABBBCFCAA...',
      'EDDDEHEDDDHEEEEEDDDCABBCCCCCBBBBAAABABBBBBBBCCCBEAABAABBCFFBAD..',
      'DDEEEDDAADDDDEEDDDEDADBCCCCCCBBBDAAAAAAABAABBBBBEAADAABCCCCBAD..',
      'DEEEDDAABBCAAEEHDDDCAAABCBBBCBBAAAAAEEDAADDAAAAAADDDDAAABBBAAD..',
      '.EEDDDAABBBCBEEEDDDDAAAABBBBCBAADBAEEAAAABAEAABDADABBCCABBAADAA.',
      '.EEDDDAABBBCIAEEDDDDAAAAABBBBBAADAEDDABBCCCCDAAEDABBCCGCAAAADABA',
      'EEEDDDDACACCIBEEDDDDDDABAABBBBAAEHEDAABBCCFCBDAEDABBCIFCEDDDDBBA',
      'EEEDEDDABBBCCAEEDDDDDDAAAAAAAAAAHDDDAAACCFFFCDEEDABBCCCCDDAEABBA',
      'EEDDEDDDAABBBADEEDDDDDDDAAAAAADAHDDDBBBCCCFCBDEEDBABBCCCAEBCADAA',
      'EEEEEDDDAAAAAADHEDDDDDDDDDAADDDDEDDDAABBCCCBAAHEDADBBCCBAEBCBDAA',
      'EEEEEDDDAAABAADDEEDDDDDDDDDDDDDEEDDDDAACCBBBBAHEDDDAABBBDEBBBDAA',
      '.EDEEEDDDDDDDDDEHEEEDDDDDDDDDEEEEEDDDDDDBBBAADEEDDDADDDDEEAAADAD',
      '..DDEEDEDDDDDDEEEEEEEEDDDDDEDEHEEEEDDDDDADADDEEEDDDDDDDDEEDADDDE',
      '....DEEEEDDDEEEEEEEDEEEEEEEEEEEHEEEEDDDDDDDDEDEEEEDDDDDEEEDDDDD.',
      '.....EEEEEEEEEHEEAEEEEEEEEEEEEHHEEEEEEEDDDDDEHJEDDEEEEEEHEDDEE..',
      '......DEEEEEEEDADAAAEEEEEDEHEEEKEEEEEEEDEEEDJEJJEEEHEED.DDEE....',
      '........EDEE....EDADDDH....EEEKKLEEEEEEEEEEH.......HHD..........',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
    ],
    key: {"A":"#3d4650","B":"#566270","C":"#77828e","D":"#2a313a","E":"#1b2027","F":"#e8eef2","G":"#c6ccd2","H":"#101318","I":"#9aa3a8","J":"#6e4e22","K":"#8a6a34","L":"#f5c24a"},
  },
};
