/**
 * Written by `tools/art/portrait.mts`. Do not edit by hand.
 *
 * Generated faces, one frame each and carrying their own colours. `PORTRAITS`
 * merges these OVER the hand-drawn rows.
 */
export type GeneratedPortrait = {
  grid: number;
  rows: string[];
  key: Record<string, string>;
};

export const GENERATED_PORTRAITS: Record<string, GeneratedPortrait> = {
  lampwright: {
    grid: 96,
    rows: [
      '................................................................................ABCCCCDCEF......',
      '...............................................................................GEHIJ...JHKL.....',
      '..............................................................................BCAF......FCEG....',
      '.............................................................................BEM..........HKJ...',
      '............................................................................FBH...........JHEN..',
      '............................................................................GHF............HBF..',
      '...........................................................................LBHF............MBG..',
      '...........................................................................OBC.............FEG..',
      '...........................................................................LGC.............PEG..',
      '...........................................................................LBC.............OEB..',
      '...........................................................................OBC.........F...QHG..',
      '...........................................................................OBC........JE..FEHJ..',
      '...........................................................................OBC........JD.ORHF...',
      '...........................................................................LBC.........SGNHF....',
      '...........................................................................LBH.........AOFIT....',
      '..................................RFKKUVQI.................................LBH.........AO..B....',
      '................................JQUKKKKKUWDFF..............................OBH.........OO..B....',
      '...............................FKVFVKKWWWWSWWXF............................LBH.........AVUFR....',
      '..............................FVFFVKWWWWWWWVWWWF...........................OBH..........FBO.....',
      '..............................YFZVBWWWWWWWWWBWWWA..........................LBH..........OTF.....',
      '..............................FZVGWWWWGWWWWWWVWWWO.........................LBH........FGGaGBF...',
      '.............................IVVKWWWWWWWWWWWWWKWWWJ........................LBH.......XQGGaBBGX..',
      '.............................AVKSWWWWWWWWWWWWWWbWWWF.......................LBH......XBFFFFFFFVL.',
      '.............................VVKWWWWWWWKWWWWWWWKVWWWI......................OBH......IBJJcaaFFTF.',
      '............................FVKVWWWWWWWWWWWWWWWdddWWJ......................OBH......FHdefGgehhO.',
      '............................QKKWWWWWWWWGVWWWddgiNPMWE......................LBH......FhejjEfjegP.',
      '...........................IVVVWWWWWWWVWWWddiFFNNNFgMF.....................LBH......FHjjjTejjhO.',
      '...........................FVVVWWWWWWVWWMdPNNNNNNNNPgM.....................OBH......FhjjkTkjehI.',
      '...........................AVVKWWWWWKWWWgFNNFNNNNNNNFdR....................LBH......FHjkkTllehF.',
      '...........................KVKWWWWWWGWWgONNNNNNNNNFNNfL....................LBH......JhjkkTlkehO.',
      '..........................FVVKWWWWWKWWgFNNNNNNNNNNNNNFJ....................LBH......JHjkkTllehF.',
      '..........................LKKKWWWWWKWdiNNNNNNNNNNNNNNFF....................OBH......FHjjkTljegF.',
      '..........................KVKKWWWWVWbiNNNNNNNNNNNNNNNNF....................OBH......JhfjeTfjedO.',
      '.........................FVNKWWWWWVWdcNNMMFNNNNNMMNNNNg....................LBH......JAFefTgfRPF.',
      '.........................XVFVWWWWWGbdFNSmmMNNNNDmmMNNFh....................OBH......JFGLLaJFBOL.',
      '........................IVKFWWWWWKWgWNNMmmMNNNNCmmMNNFh....................LBH.......FFGUaGGFN..',
      '........................FVFKWWWWWbWdPNNNhhFNNNNNhhONNNgJ...................LBH..........QQK.....',
      '........................VVFKWWWWWWbdFFNNNNFNNNNNNNNNNNdF...................LBH..................',
      '.......................IVVNVWWWWVWhcNFNNNNNNNNNNNNNNNNMI...................LBH..................',
      '.......................FVVNWWWWWVWdFNNNNNNNNNNNNNNNNNNFF...................LBH..................',
      '.......................PVVNWWWWVWWgNNNNNNNNNNNNNNNNNNNFF...................OBH..................',
      '.......................FVVFVWWWVWdFNNNNNNNNFNNNNNNNNNNOH...................OBH..................',
      '.......................NVVFKWWWVWfPFNNNNNNFFFNNNNNNNNNOh...................OBH..................',
      '.......................OKVNFWWWVDfNNNNNNNNNFFNNNNNNNNNFg...................LBH..................',
      '.......................FQKKQKWWKSnNNNNFFNNFFNNNNNNNNNNFg...................OBH..................',
      '.......................FFNKFKWnFDnNNNNFNNNFFFNNNNNNNNNNH...................LBH..................',
      '......................FKFNFNKKGFnnNNNNNNNNNFFNNNNNNNNNNCJ..................OBH..................',
      '...................RDFFKKVNNFVVNBcFNNNNNNNNNFNNNNNNNNNFCJ..................OBH..................',
      '..................FPZCERFVVNNFVFKCCFNNNNNNNNNNNNNNNNNNNCJ..................LBH..................',
      '.................FFFNVVWNNNKFNVLKgHPFNNNNNNNFNNNNNNNNFFfA..................LBH..................',
      '...............IGNNNNVVVWHPFVKNFZhFgNNNNNNNNNNNNNNNNNKFh...................OBH..................',
      '..............NKKBnDNNVUSSDiNKVNFNFPiFNNNNNNNNNNNNNNFFhF...................LBH..................',
      '.............OPPFFNFPFFDFMdiNNFKKFFFdNVKNNNNNNNNNNNNCIg....................OBH..................',
      '............FKVKFNPNFMFVQWWJnnPSUnbFFhFKKNNNNNNNNNNPMNOI...................LBH..................',
      '...........IFNNNNNNNNFNNVWFcdMSGNKKWNFFgFVVFNNNNNNNSKgOPI..................OBH..................',
      '...........FVVKWWWWDFQNNUNNnWcFFVOFVUSFFgFNVVVNNFVWZFMFCF..................LBH..................',
      '..........NVVKWWWWKVVPVNFNVKcRCNFKSFVVWFNFHFFVVbKUZFhNFhOF.................LBH..................',
      '.........LQVbKWWVKWZFFNNcNVKFKgXFFKbLVGbNNFhgMFNNNFgONFgFg.................OBH..................',
      '.........FSWVVVKVVVNFUVKBFVNFFKWFNVKDQVbWNNNNPghhFgFFFFgggF................OBH..................',
      '........FKWVVVQNNNFSnGcNNNNNFFYWbGFKVFVKbbNNNNFPgdgNNNDggdF................LBH..................',
      '........NMVIFNFKWWZGNNiVKFNNSNFBbFBFKKPVKVWWNNNNNNNNNFWfgGhN...............OBH..................',
      '.......IFGFNNNKKKKKFNKWWFXnFSNNKWWFiFVKFFVVKWWFNNNNNNFWdFCHN...............LBH..................',
      '.......NFNNLKVVFFNNUWSWnFBNbFNNNUWWVSFKKWFVVVVWWNNNNNWgGNEHF...............OBH..................',
      '.......IFFWSVVFNNNVWVWDQWFFSNNNNVKWFKWFKVWiKVVKWWWWWWbhKNgMF...............LBH..................',
      '........OIbNNFFVVKbKEVPFiNWWNNNFFUVWQGWFKVWVPFVKVnWUKBVFFhSF...............OBH..................',
      '........OSKVVVVVKWUbVKPMDFWFNNFFGFVKbVcSFVVWWWFVVKVVVKVFNhFF...............LBH..................',
      '........QVVVVVVVWWWVVFnKNKWFKNFFFEFFUFVUNNFVKKWWIVVFZFNFMdFW...............OBH..................',
      '.......IWKKKKVVWWWVVKPVVFGWNFVNVFiNNNKFKWNNFVKSWWNNNNNNFWhFWI..............LBH..................',
      '.......LVVVVVWWWWVKKFMVNNWbFNNNKFGWFFNNZVDSNNFKKVWFNNNNiMHFSI..............LBH..................',
      '.......KVVVVWWWWbKKKSKVNUWFONSNKFVbNVVNNPVWSFNFVVWWWFNPDGiPBMI.............JBH..................',
      '......LKVKKWWWWWWKKFKKPVWWFNKKVVNVbNKFFFFVVVWNNFFVFVWWbVWFVKMR............NLRH..................',
      '......FVVVKWWVWVVKKKWKPUWFNVVVKKKFbFVnKFNNVVVWFWFFFVKbKVWFVKHhI..........dhggNIII...............',
      '......OVVKWWWSVWVKFWbNNEbbFFFFKVKNVFVWQRNNFNKKWWbFNFFKKWDNKSMFCP........SMWWgMcddF..............',
      '......KKVKWWbVWVKFWWVFVEWNFOKKNPVNKWVWFWNNZNNVVKGWWKKKKbNVMNNgUCFMMNNNFFhURUWdIWWF..............',
      '.....IVKKWWWKWVVGNWWVFVKWNNFFVKVNNVWFVWXbNNSNFVFKZbWcVGNFDnFbAWFWWWdSdbgWWIFSSXnCF..............',
      '.....FVVKWWVVWKWFWWVNFKWNFFFUFKVNNVKFVWZVnFnWNNNVFKKKWbFUnFSFMcPWbbWWWFfWWBFcDIIfh..............',
      '.....OVVKWWVSVVSWWSVFVWWFFFNFKVVKNFKWNbFVnFKWFNNFNNKKBFNFFWWFSFhWWbhSDIbWWBNPFXWWHI.............',
      '.....OVKbWVGVVKOWWVKNKbWFFFFKVVVVFNKWNnFUDFFGWPFNNNNNNNNPFWFSXFWWWWWWWJbWWKNcCWSCBF.............',
      '.....VKKWWWKVVJWWWKNFVWbFNNVFGVKVKNKbFVWUSFFVSFKFNNNNNNNUFGFDMFWWWWWWGWWBQNNFFFAgF..............',
      '....OVVbWQVKKFWWWKVFFKWFNNFUOFFVPFNFKbVWFBWNVVWFKNNVVVUFVXKFKMFWWWWWWUWWRKVFnMgfWb..............',
      '....FKVWWWVVVVSWbKNNKWWNNNFNKKNKVNNNVWVKFKbNFKKFKKNVVKWFPKVFKNFbWWWbWIVWWWVNcnnccF..............',
      '....VKKWVVVKFKWWVKNNKWWNNNNNNKVVKFNFNWFKSKbWFNKWLKKFKWWFNKVNKFNDWFFWWDFKWVVNFFOOdR..............',
      '...FVKVVWKKFQWWbKNNFKWWNNNFDNNNFVcNNNVFKSFSSNFVKWFKNNVWFNKVNKNNFbKUKVFiFKKVNKDMMWI..............',
      '...NVKWVGVKFVWWKKNNNWWWNNNVKKNNPFNNNFKFFbFVWFQFVbFVKFKSWNFVFVKNNKKKLBEKFIFFFOFPOI...............',
      '...XKKWWVVKNKWWKKFNNWWFNFFFFFKFVQZFNNUWFKWNDFVFVKWFVVFKWNFVVNVNNQOKVDFR....OGH..................',
      '...KKWWKVVVVbWWKFFKFWWFNNFFNNPNFQFBNNGbPVSFKNFFFKWWFVNFQFNFKNVKNNFL........LBH..................',
      '..LVKWKKKKNKbWVNFKNDWWNNFFNNKNVFFPNiNNSWVWNQWNDNIUWWVKVVKNNVVNNF...........OGH..................',
      '..IVVWVKKNNKWKVFNKFbWWNNNFNFKKVVVVVKNNKWKVWYSNPKFVVWIVPVVFFNFFI............LGH..................',
      '..LVWWVKKFFWWKVFNVNWWWNNNNNNYFKKVVUNFZVWFKSFnNNBPFVVRKKFKF.................OGH..................',
      '..KKbVKKKNVWWKFNKFKWWFNNNNNKFFVbVVKFNNVbWKbUBWNVWNFVWWVFVF.................LBH..................',
      '..KWbVVKVNVWKKFNKNKWWNNNNNFNNVNVFUUiNNYVWQbWUbFVcWFNUWWKFF.................OBH..................',
      '.JVWKKKKNNKKKKNKKFKWWFNNNNNFNNFPNFFFNNFVWQVbNSFFVncNKWWWVP.................LBH..................',
      '.IUWVVKVFFWKKNNKNKWWWNNNNNNNNNNFNVFPNNNVWFVbPZNNPVbNFKKWWZ.................OBH..................',
      '.FbWKVKKFWWKKNFKFVWWWNNNNNNNNNNFVKPKNNNVWPVGWNSNNFKSNFKKWW.................LGH..................',
      '.YWWKKKNNWWVNNPVNKWWFNNNNNNNNNNiQKKFDNNVbFNKSFEbNNVMNNFVKWI................LGH..................',
      'JbWKKKKNKWUFFNKVFKWSFFFNNNNNFcBFFKKNNNNFWKNKbYFSFFFVWFNNKKI................JBH..................',
    ],
    key: {"A":"#040304","B":"#482c1e","C":"#6a3b1b","D":"#53271a","E":"#512c1a","F":"#00000a","G":"#3a2a1a","H":"#89451e","I":"#010615","J":"#020506","K":"#3a2d1e","L":"#050611","M":"#7e3317","N":"#000116","O":"#06020a","P":"#060213","Q":"#2d2620","R":"#070b0f","S":"#672611","T":"#4f3b2b","U":"#31221a","V":"#302c20","W":"#712a18","X":"#1b0f0e","Y":"#1e1d17","Z":"#272519","a":"#644d37","b":"#682717","c":"#3a2112","d":"#b56824","e":"#e89746","f":"#c57928","g":"#a95920","h":"#9a491d","i":"#511c13","j":"#f3ad54","k":"#fdefa7","l":"#fff5bb","m":"#fef592","n":"#47291a"},
  },
};
