/**
 * Written by `tools/art/portrait.mts`. Do not edit by hand.
 *
 * Effect art, drawn in the WORLD rather than in a panel: cropped to its own
 * ink and squared up, so the picture's edges are the effect's edges and the
 * renderer can pin it by them. One frame each, carrying their own
 * colours, and only Pixi draws one — canvas2d has no sprites.
 */
export type GeneratedVfx = {
  grid: number;
  rows: string[];
  key: Record<string, string>;
};

export const VFX_ART: Record<string, GeneratedVfx> = {
  arrow: {
    grid: 48,
    rows: [
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      'AABBBBAB........................................',
      '.CDECFBCD...............................BEADD...',
      '.CCCFCCACG...............................HIIJEFF',
      '..BGBBGBGGAEEEEEEEEEEEEEEEEEEEEEEEEEEFEFFBBJIDA.',
      '.ECACCBDDC..............................ABFFD...',
      'AFBAABFE........................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
      '................................................',
    ],
    key: {"A":"#101318","B":"#07080a","C":"#566270","D":"#3d4650","E":"#2a313a","F":"#1b2027","G":"#0b1a0e","H":"#2a1c0c","I":"#77828e","J":"#9aa3a8"},
  },
  storm: {
    grid: 64,
    rows: [
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '.............................AABBAA.............................',
      '...........................AABBBBAAAA...........................',
      '..........................AABBBCCCCBBD..........................',
      '.........................AABBBBCCCCCBAA.........................',
      '......................DEDAABBBCCCFFFCCBD........................',
      '....................DEDDDDACCBCCCCCFFCBB........................',
      '...................DEDDDDDABCCBCCCCCCCBAADDD....................',
      '...................EEEDADDDBCCBBCCCCCCBADAAAAA..................',
      '.................DEEEDDDDDABCCBBBCCCCCAAAABBAABB................',
      '................DDEEEDDDDDDABBBBBCCCCBDDBCBBBCCB................',
      '...............DDDEEEEDDDDDABBBABBBBBAEABCCCCCCC................',
      '..............ADDEEDEEEDDDDADBCBBCBAAEDABCCCCFCCE...............',
      '..............DDDDEEEEEEDECADAAAAAAAAEDABBCCCGFCA...............',
      '.............DDEEEDDAAADDEDDDDADAAAADEDDBBCCCCCBBD..............',
      '.............EDDEDADACAAEEDDDDDDDDADDEDABCCCBCCBBD..............',
      '.........DEEEEDDDDDDAAAAEEDDDDDDDDDDEEDABBBBBBBDAAAAA...........',
      '........DEEDEEDEDDDAAABAEEEEEDDDDEEEEHDDACCCBDDDABBBAAD.........',
      '.......DDDDDDEEEEDDDAABAEEEEEEEEEEDEDEEEAAADDDAABCCCBBAD........',
      '......DDAAABBDHEEEDDDAADHHDDHEEEDAAABBAADAADAAAABCCCCCBB........',
      '......EDABCCCDDDEEEDDDDDHEEEEDEDAAABCCBBADADAAAABCCFFCBBD.......',
      '.....DEDABCCFDAEEEEEEDAAAEEEEEEABBBBBCCFCADDAAABCCCCFCCBA.......',
      '.....EDDDABBBAAEEDAABBBCBBBBEEDABBBCCCCCCBADAAABBCCCCCBBAD......',
      '...EEEDDAAAAAADHDDAABBCCCCCCBADAABCCCCCCCBAADDCABBBCCBBBAE......',
      '..DDDEEDDDAAAEEEDDDABCCCCFFCCBDDBBBCCCCCCBBBBDAACABCBBBAED......',
      '.EDDDEEEDEEEEEDEDDDDBBBCCFFFCBADBBBBBBBCBBBCCBAEBBBBBAAADA......',
      '.EDDEEEEEEEEDDEEDDDDDBBCCIFFCBBAAAAABBBBCBBCCICAAAAAAABBBBBD....',
      'DDDDEEEEEHHHHEEEDDDDABBCCCCCCCBBABAAABBBBBCCCFCBAAAAABBBCFCAA...',
      'EDDDEHEDDDHEEEEEDDDCABBCCCCCBBBBAAABABBBBBBBCCCBEAABAABBCFFBAD..',
      'DDEEEDDAADDDDEEDDDEDADBCCCCCCBBBDAAAAAAABAABBBBBEAADAABCCCCBAD..',
      'DEEEDDAABBCAAEEHDDDCAAABCBBBCBBAAAAAEEDAADDAAAAAADDDDAAABBBAAD..',
      '.EEDDDAABBBCBEEEDDDDAAAABBBBCBAADBAEEAAAABAEAABDADABBCCABBAADAA.',
      '.EEDDDAABBBCIAEEDDDDAAAAABBBBBAADAEDDABBCCCCDAAEDABBCCGCAAAADABA',
      'EEEDDDDACACCIBEEDDDDDDABAABBBBAAEHEDAABBCCFCBDAEDABBCIFCEDDDDBBA',
      'EEEDEDDABBBCCAEEDDDDDDAAAAAAAAAAHDDDAAACCFFFCDEEDABBCCCCDDAEABBA',
      'EEDDEDDDAABBBADEEDDDDDDDAAAAAADAHDDDBBBCCCFCBDEEDBABBCCCAEBCADAA',
      'EEEEEDDDAAAAAADHEDDDDDDDDDAADDDDEDDDAABBCCCBAAHEDADBBCCBAEBCBDAA',
      'EEEEEDDDAAABAADDEEDDDDDDDDDDDDDEEDDDDAACCBBBBAHEDDDAABBBDEBBBDAA',
      '.EDEEEDDDDDDDDDEHEEEDDDDDDDDDEEEEEDDDDDDBBBAADEEDDDADDDDEEAAADAD',
      '..DDEEDEDDDDDDEEEEEEEEDDDDDEDEHEEEEDDDDDADADDEEEDDDDDDDDEEDADDDE',
      '....DEEEEDDDEEEEEEEDEEEEEEEEEEEHEEEEDDDDDDDDEDEEEEDDDDDEEEDDDDD.',
      '.....EEEEEEEEEHEEAEEEEEEEEEEEEHHEEEEEEEDDDDDEHJEDDEEEEEEHEDDEE..',
      '......DEEEEEEEDADAAAEEEEEDEHEEEKEEEEEEEDEEEDJEJJEEEHEED.DDEE....',
      '........EDEE....EDADDDH....EEEKKLEEEEEEEEEEH.......HHD..........',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
    ],
    key: {"A":"#3d4650","B":"#566270","C":"#77828e","D":"#2a313a","E":"#1b2027","F":"#e8eef2","G":"#c6ccd2","H":"#101318","I":"#9aa3a8","J":"#6e4e22","K":"#8a6a34","L":"#f5c24a"},
  },
  poison_pool: {
    grid: 48,
    rows: [
      '................................................',
      '................................................',
      '...................AA...........................',
      '....................A........B..................',
      '...........CA...D...ABC.....CB......EFC.........',
      '............G......AHIIIAAAAJA.....AKBC.........',
      '....CIC.....B.....AIIFFJIIIJJAI....BEA..........',
      '.....LEH.AA.AF..BIJDDDDDMIJJJIA..AI.............',
      '.......AA.C.AIBDDIDDDIDDDDIINNGBIHO........EAA..',
      '........AA..HJJIDMDIDMDDDIDDLBDIFB..M.....HBIA..',
      '.....M..ALFIJIDIDDDIDDMDIDDDIIDDDD...IC..AIIH...',
      '........ADIBDMIBINDNDDDNMDDDDDDDDGA.IA...BAA....',
      '.......M.BIBDDDNDNDMDDDDDIDDNDIIDNPPI..AB.......',
      '...AI...OBIDDDDNIDIDIDDDDDNDDDDDDDMJNCBA........',
      '.G...BABMIMDDDDDDIMIMIDIDDDDDDDDDDDIDIA..KA.....',
      '.....AHFQDDDMDMMDDINDDDDDDDDDIDDMNDDDDIAAC......',
      '.....BBLLDDDNDINDDDIDMDDDNDDDDDMMDDDLDNA........',
      'AA...BIIBDDDMMDIDDDMDIIDDDDDDDDDDDNNFIDA........',
      '.CKCENDNNDDMDIODDMDDDDDDDDDDDIIDNDDNHDDI..C.....',
      '...AIDDDDDDNDDIDDNDDDDDDDDDDDIDDDIDDDMIDIB......',
      '....HDNDNDDDDINDDDDDDDDDDDDDDDDDDIDMDDDNC.......',
      '...AHDDDDDNDDDIDDDDDMDDDDDDDDNNDNMDDIMMN........',
      '...HINIIDDINDDDIMDDDDDDDNNNDDDDDDNMDDMDDAC......',
      '...BIDDKDDDDDDDDMNDMDDDDDDDDDDNDDDDNDMNMNFC...I.',
      '...BIBIIDMIDDDDDMDDDNINDDDMDDDDDDDDDIDIMDDIAAA..',
      '...HBBNMIDMNDNNDDMIDMDDIDIDDDIDNDIDNDNDMDDJIC...',
      '...BRBDIIDDDMDIDDDDDDDDDDDDDDDDDDIDMDMDDMMDGAJ.C',
      '...CBIBNDDDDNDIDIDDDDDDDDDDDDBDDMNDIDDDNDDIGCM..',
      '....HIIIIIDIIDDDDDDDDDDDMDDDDMDMDNDDDDMIDDDGIE..',
      '....CIIBDNNNIIDDIPDNDDDDDDDDDDDDDIDNDBEIDDIGINC.',
      '.....IBBIDMDIDNDDDDDFDDDDDDDDMDDNDDDDDDIDDDIB...',
      '.....HBBBIIIIINIDDDIHDIDNIDDDIDDIDMININDIIDIB...',
      '....I..HIBQLDDDIDDDNNDIDDMNDDDDDDDMDDIDINDDBI.M.',
      '...AA..ABBDHDIDMDDDMDDDDDIIIDDDDNMIDIMMDNDDBB...',
      '...A...IHBIBDDDDBLIDDDDMDDDDDMDDMDDIDNDMDIBILNA.',
      '.....CD..ABIIBDDIBIMDIDDDNDDDIDDIMDDDDIMIBIB..AA',
      '.....AC...HKHIIBDNDIDIIMNDDDDDNDMNNDIDDDBIIFA...',
      '.........ANAABBIBBIIIININDDDDNDNNIDDDDMBIBHAAA..',
      '.........HE.EHBIBIBBBBBBBDDNDNMDNIMIDIIBIBA.....',
      '........ACM..CBCHBIIIIIIBIBBDIDDMDIHIBBIHC......',
      '.......AA....EN..AAAHIBABIIBBBINNBBBIIIB........',
      '.....EIB.....IA.....ABB..CBIIIIBIBIIHEHB........',
      '....BJGE.....E.......BA...CBAHIHAAAA...B.....M..',
      '...CBNNE.............C.....A.ABH.......AC.......',
      '...AIBH.........CH...DA.G.CI..IA........NC......',
      '....AC...........C...AA...II..AACIC..M..AIC.....',
      '...............................F.A.......BHA....',
      '................................................',
    ],
    key: {"A":"#07080a","B":"#2a313a","C":"#0b1a0e","D":"#47792b","E":"#101318","F":"#ffe9a8","G":"#9ccb4e","H":"#1b2027","I":"#3d4650","J":"#7cb03d","K":"#5f9433","L":"#16301a","M":"#566270","N":"#325e24","O":"#c6ccd2","P":"#22471f","Q":"#c3e27a","R":"#77828e"},
  },
  poison_drop: {
    grid: 48,
    rows: [
      '.........................A......................',
      '.........................A......................',
      '.........................A......................',
      '.........................A......................',
      '.........................A......................',
      '.........................A......................',
      '.........................A......................',
      '.........................A......................',
      '.........................A......................',
      '.........................A......................',
      '.........................B......................',
      '.........................C......................',
      '........................AC......................',
      '........................CDB.....................',
      '........................EFB.....................',
      '.......................BCGB.....................',
      '.......................AHGB.....................',
      '.......................ACHCB....................',
      '.......................ACHAA....................',
      '.......................IJKHCE...................',
      '.......................DLCCCA...................',
      '.......................FGCCCCA..................',
      '......................AGCCCCGA..................',
      '.....................GGGCCCCAC..................',
      '....................BCMGGCCCCC..................',
      '...................EHGGCCECCCC..................',
      '..................AGFGGGECCCCCA.................',
      '.................AHFEGECCCCCCCHB................',
      '................BGGFFCGGCCCCCCGCA...............',
      '...............NCFOOFGGGCCCCCCCCA...............',
      '...............CPDOFGGCCCCCCCCCACA..............',
      '..............CCGFFGGGGCCCCCCHCKAC..............',
      '..............CCGFGGCGCCCCCCCCCCPG..............',
      '..............CCCGGCECCCCCCCCCCCCGB.............',
      '.............EGEECCCCCACHCCCCCCCCQB.............',
      '.............EGCCCCCEECCCCECCGCCCCB.............',
      '.............BGCCCCCECCCCCCCCCCCCCB.............',
      '..............ACCCCCACCCCCCECCCCCGH.............',
      '..............ACCCCCCCCCCCCCCCCCCGE.............',
      '..............AEHCCCCCCECCCCCCCCCCC.............',
      '...............CCCCCDCCCCCCCCCCCCH..............',
      '...............AECCCCCCCCCCCCECCCB..............',
      '................EICIIIIAECCCCECKA...........G...',
      '....QB...........BRCCCIKCCCCCCIE................',
      '..................ACKACCCCCAKAA.................',
      '.........AAAAAK.................................',
      '........HPKCHCA.................................',
      '...B....KOGAAAA.................................',
    ],
    key: {"A":"#07080a","B":"#101318","C":"#16301a","D":"#3d4650","E":"#0b1a0e","F":"#c3e27a","G":"#5f9433","H":"#22471f","I":"#566270","J":"#9aa3a8","K":"#47792b","L":"#9ccb4e","M":"#e8eef2","N":"#1b2027","O":"#ffffff","P":"#325e24","Q":"#7cb03d","R":"#2a313a"},
  },
  burst: {
    grid: 48,
    rows: [
      '................................................',
      '..................AB............................',
      '..................CD............................',
      '...........................E....................',
      '......................F............EBA..........',
      '....................GH......EAB...GEBB..........',
      '...........E....H...........IAA....EBB..........',
      '...........AJ...............EAI....HKKE.........',
      '...........HH...L...BJA....DB.M.................',
      '...A..........DB..GKEEKDAAHEBBBB................',
      '...H.........BBBAAEHHHH...CKIBABD...............',
      '............HBAAH.........DEEHEA.H..............',
      '......K....NKKEE............HHE.AH..C...........',
      '...........HHCEE.................H..MH..........',
      '......A..AAB.KEK..................KB............',
      '......K.BAAH......................OH......A.....',
      '........COEE.......................HE.......L...',
      '.H......AKP.........................HKM.....H...',
      '........I...........................NDQ..A......',
      '.....................................A..........',
      '......EAA...........................EEBB....K...',
      '......EAB...........................EELB........',
      '.J....KO............................EEAB........',
      'EB...L.A............................EEAA........',
      '....RH.A..............................KH.R...ILS',
      '......IJB............................AA.....EHEA',
      '.....EEAB...........................ABAE....CKKH',
      '.....EEIB...........................EBBE.....KEE',
      '......EEBA...........................CKKR.......',
      '......EEAK...........................HNB........',
      '......HEE............................AAH........',
      '........A...........................MH..........',
      '........HIBB......................ABHI...HAB....',
      '....AA..HEIL.....................GHII....KIA....',
      '....HH...EHK..................BAKAKOH...........',
      '..........EA................BBBB.KAT............',
      '.BB.........DBA.............BBBBI..K..EB........',
      'EAA.........EILL............ABALEE..............',
      '.H..........EEHEHABBA.......KEEEK...............',
      '............KEEECHAAI.M.LBBAAKH.I..D............',
      '..................HEKD..EEEKQAI..P....B.........',
      '...................K....KK..KIA...AB..M.........',
      '.................................HII............',
      '.......................G..........EI............',
      '..............AL...E............................',
      '..............EA................................',
      '................................I...............',
      '................................H...............',
    ],
    key: {"A":"#d9a441","B":"#f5c24a","C":"#0b1a0e","D":"#8a6a34","E":"#6e4e22","F":"#566270","G":"#2a313a","H":"#4a3418","I":"#8a6c25","J":"#ffffff","K":"#2a1c0c","L":"#ffe9a8","M":"#1b2027","N":"#101318","O":"#07080a","P":"#3d4650","Q":"#c3e27a","R":"#16301a","S":"#e8eef2","T":"#77828e"},
  },
};
