/**
 * Bundle the art desk into ONE markdown file to hand the art director.
 *
 * Astra may have no access to this repository, so the handoff cannot be a
 * folder of links. This concatenates the desk into `art/astra-pack.md` and
 * lists the pictures to attach beside it.
 *
 *   node tools/astra-pack.mjs
 */
import { readFileSync, writeFileSync, readdirSync, existsSync, statSync } from 'node:fs';

const DESK = ['ASTRA.md', 'CONTRACT.md', 'PIPELINE.md', 'INVENTORY.md', 'QUESTIONS.md'];
const parts = [];
const attach = [];

parts.push(`# Crystal Core — art handoff pack

Everything the art director needs, in one file. Generated by
\`node tools/astra-pack.mjs\` on ${new Date().toISOString().slice(0, 10)} —
regenerate it whenever the desk changes.

Attach the pictures listed at the end; this file references them by name.
`);

for (const name of DESK) {
  const at = `art/${name}`;
  if (!existsSync(at)) continue;
  parts.push(`\n\n---\n\n# ── ${name} ──\n\n${readFileSync(at, 'utf8')}`);
}

const briefs = existsSync('art/briefs')
  ? readdirSync('art/briefs').filter((f) => f.endsWith('.md') && f !== 'README.md').sort()
  : [];
if (briefs.length) {
  parts.push('\n\n---\n\n# ── OPEN BRIEFS ──\n');
  for (const f of briefs) {
    const body = readFileSync(`art/briefs/${f}`, 'utf8');
    // A finished or overtaken brief is history; the pack carries what is live.
    if (/\*\*Status:\*\*\s*`?(integrated|dropped|superseded)/.test(body)) continue;
    parts.push(`\n\n## ${f}\n\n${body}`);
    // A brief's pictures sit beside it under the same NUMBER — not the same
    // stem, so a picture can be named for what it shows.
    const num = f.slice(0, 4);
    for (const p of readdirSync('art/briefs')) {
      if (p.startsWith(num) && !p.endsWith('.md')) attach.push(`art/briefs/${p}`);
    }
  }
}

const decisions = existsSync('art/decisions')
  ? readdirSync('art/decisions').filter((f) => f.endsWith('.md') && f !== 'README.md').sort()
  : [];
if (decisions.length) {
  parts.push('\n\n---\n\n# ── STANDING DECISIONS ──\n');
  for (const f of decisions) parts.push(`\n\n## ${f}\n\n${readFileSync(`art/decisions/${f}`, 'utf8')}`);
}

if (attach.length) {
  parts.push(`\n\n---\n\n# ── ATTACH THESE ──\n\n${attach.map((a) => `- \`${a}\``).join('\n')}\n`);
}

const out = parts.join('');
writeFileSync('art/astra-pack.md', out);
const kb = (statSync('art/astra-pack.md').size / 1024).toFixed(0);
console.log(`art/astra-pack.md  ${kb} KB, ${briefs.length} brief(s), ${decisions.length} decision(s)`);
for (const a of attach) console.log(`  attach: ${a}`);
